fix(messages): show past messages in correct order
Satellite-im/Uplink pull request #1053
Opened 2023-07-27 13:44 UTC by sdwoodbury

### What this PR does 📖

- fixes the lazy loading of messages. Chats are still only initialized with a few messages at first but now as more messages are fetched, they are displayed in order. 
- This fix isn't as lazy as it could be, but doing it this way prevents bugs arising from extra events getting triggered. 
- This may be good for a temporary solution, until we figure out how to determine when the user has scrolled to the end of a container. Without that, infinite scrolling will be hacky at best. 

### Which issue(s) this PR fixes 🔨

- Resolve #1024 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-07-27 20:14 UTC, dariusc93 approved these changes
LGTM, though it makes me wonder if we should switch over to using `MessagePage` instead and as one scroll up (or down from the current page of messages) that it would get the next (or previous) set.

2023-07-27 20:16 UTC, sdwoodbury commented
> LGTM, though it makes me wonder if we should switch over to using `MessagePage` instead and as one scroll up (or down from the current page of messages) that it would get the next (or previous) set.

I'd like that. I'm hoping we could use an approach like that once I figure out how to handle scrolling in Dioxus.

2023-07-27 22:06 UTC, stavares843 requested changes
https://github.com/Satellite-im/Uplink/assets/29093946/75d65167-f8cd-47fc-b0a1-5030244b8b0b




if you notice the scroll

when i switch chats

it goes up and down even thought when i manually scroll theres no new messages

so not sure what he is trying to fetch

i know that is the latest message and is correct but

theres something in the fetch that isn't behaving properly


macOS, m1

2023-07-27 22:18 UTC, stavares843 approved these changes

2023-07-27 22:18 UTC, stavares843 commented on common/src/warp_runner/ui_adapter/mod.rs
> +    // );
do we need this part? 🔨

2023-07-27 23:15 UTC, phillsatellite approved these changes

2023-07-28 11:23 UTC, stavares843 commented
added a minor comment but merging

2023-07-28 11:23 UTC, merged