feat(ui): Improve call UIs
Satellite-im/Uplink pull request #1157
Opened 2023-08-23 14:31 UTC by Flemmli97

### What this PR does 📖

- Adjust various call ui to match the figma in the linked issue

### Which issue(s) this PR fixes 🔨

- Resolve  #1135

### Additional comments 🎤

The figma also shows a call ui in the chat (not sidebar) but we
1. dont have anything similar currently in uplink (as far as i can tell)
2. i see it as kinda redundant since we already have it in the sidebar. maybe someone else can give their input on this

2023-08-24 22:34 UTC, stavares843 reviewed
![image](https://github.com/Satellite-im/Uplink/assets/29093946/ef8af4ca-5d4c-4d65-b127-e8bacca3f9a2)

if you go to a group > call > remove people > avatar doesn't get updated in the call

macOS, m1

2023-08-24 22:34 UTC, stavares843 reviewed
if you go to a group where is only 1 person > call > no avatar appears

![image](https://github.com/Satellite-im/Uplink/assets/29093946/15159fd8-8499-4e7d-9813-aef5f337a7ed)


macOS, m1

2023-08-24 22:50 UTC, phillsatellite commented
Somethings I noticed

On light mode, should we have the call background be black? Was thinking when we have video the white background might be intrusive  

<img width="977" alt="Screenshot 2023-08-24 at 6 35 43 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/bd0ee9eb-d5c1-43f8-9f3d-dc9a5bfedcb1">

Also noticed if the user only has 1 chat and they go to a different page the call pop out never appears. This also happens if the user navigates to a different page from the current call chat 

https://github.com/Satellite-im/Uplink/assets/29093946/24b223be-1029-4d1b-9d83-6a88bb82c26e



Also talked with Sara and we thought the call pop out could be a little smaller 

<img width="301" alt="Screenshot 2023-08-24 at 6 39 30 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/c8117fdb-a4eb-48ff-95d5-e4d778147178">

<img width="411" alt="Screenshot 2023-08-24 at 6 38 53 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/af015e76-e097-4223-bfa8-249e77ef1f84">

2023-08-25 11:48 UTC, Flemmli97 commented
> if you go to a group where is only 1 person > call > no avatar appears
> 
> ![image](https://user-images.githubusercontent.com/29093946/263120798-15159fd8-8499-4e7d-9813-aef5f337a7ed.png)
> 
> macOS, m1

yes cause it displays all members in the call except oneself

2023-08-25 15:55 UTC, Flemmli97 commented
> ![image](https://user-images.githubusercontent.com/29093946/263120722-ef8af4ca-5d4c-4d65-b127-e8bacca3f9a2.png)
> 
> if you go to a group > call > remove people > avatar doesn't get updated in the call
> 
> macOS, m1

ive made it so it gets updated now but while doing so i found some problems with it:
currently if you remove someone from a group while they are in the call it does not terminate the call. regardless on the person who was removed or the person in the call.
so the person removed from the group is still in the call and if the group only has 1 user (the owner e.g.) left the call is still ongoing.

the reverse also has a problem:
if you add someone else to a group while in the call that other person will not be send a call request and thus also is not added to the active call. idk what behavior we want here.

also since those problems are not ui related but functionality related my suggestion is to put this in a new issue with a new pr

2023-08-25 16:05 UTC, stavares843 commented
even thought the UI added also includes functionality, after discussing with the team, we have decided to fix the issue where you remove/add users in the call for a separate ticket

2023-08-25 16:42 UTC, Flemmli97 commented
> Somethings I noticed
> 
> On light mode, should we have the call background be black? Was thinking when we have video the white background might be intrusive
> 
> <img alt="Screenshot 2023-08-24 at 6 35 43 PM" width="977" src="https://user-images.githubusercontent.com/93608357/263120944-bd0ee9eb-d5c1-43f8-9f3d-dc9a5bfedcb1.png">
> Also noticed if the user only has 1 chat and they go to a different page the call pop out never appears. This also happens if the user navigates to a different page from the current call chat
> 
>  Screen_Recording_2023-08-24_at_5.48.43_PM.mov 
> 
> Also talked with Sara and we thought the call pop out could be a little smaller
> 
> <img alt="Screenshot 2023-08-24 at 6 39 30 PM" width="301" src="https://user-images.githubusercontent.com/93608357/263121521-c8117fdb-a4eb-48ff-95d5-e4d778147178.png"> <img alt="Screenshot 2023-08-24 at 6 38 53 PM" width="411" src="https://user-images.githubusercontent.com/93608357/263121536-af015e76-e097-4223-bfa8-249e77ef1f84.png">

what is take on the background color now? as it seems you have phrased it like a question.

2023-08-25 20:47 UTC, stavares843 commented
yes @Flemmli97 could you add the same background color as the one we use here - the dark grey in the light mode please?


![image](https://github.com/Satellite-im/Uplink/assets/29093946/5ac8f5d3-c2f3-46fa-8ad1-d2c821aaf71b)

2023-08-28 14:57 UTC, sdwoodbury requested changes, later dismissed
We should probably move `components/calldialog` into `components/media`. 

I found that once both sides join the call, the UI looks different depending on who offered the call.

if they offer and you answer - looks like this wasn't updated to reflect the new UI
![image](https://github.com/Satellite-im/Uplink/assets/8636602/edd4d537-8e86-431b-81e5-3534633f430e)

if you offer and they answer - should probably show both participants but I could be wrong
![image](https://github.com/Satellite-im/Uplink/assets/8636602/4ae4815b-af52-4289-8eb0-667bcabc0847)

2023-08-28 14:57 UTC, sdwoodbury commented on common/src/state/call.rs
> +    fn remove_participants(&mut self, id: DID) {
the function name should use the singular noun  - `remove_participant` unless it takes a `Vec` or similar.

2023-08-28 15:49 UTC, Flemmli97 commented
> We should probably move `components/calldialog` into `components/media`.
> 
> I found that once both sides join the call, the UI looks different depending on who offered the call.
> 
> if they offer and you answer - looks like this wasn't updated to reflect the new UI ![image](https://user-images.githubusercontent.com/8636602/263736425-edd4d537-8e86-431b-81e5-3534633f430e.png)
> 
> if you offer and they answer - should probably show both participants but I could be wrong ![image](https://user-images.githubusercontent.com/8636602/263736661-4ae4815b-af52-4289-8eb0-667bcabc0847.png)

can you show a more concrete example? as for me it doesnt matter who called. the ui looks the same
when getting called:
<img width="938" alt="Screenshot 2023-08-28 at 17 46 02" src="https://github.com/Satellite-im/Uplink/assets/34157027/ed6da84e-c6ae-4670-a427-32564c68cc05">
<img width="949" alt="Screenshot 2023-08-28 at 17 46 09" src="https://github.com/Satellite-im/Uplink/assets/34157027/6f138a94-55db-4d1a-9395-3024f053a271">
<img width="937" alt="Screenshot 2023-08-28 at 17 46 17" src="https://github.com/Satellite-im/Uplink/assets/34157027/3d0bbf55-f445-4dc6-add6-a10fb2adef33">
<img width="942" alt="Screenshot 2023-08-28 at 17 46 23" src="https://github.com/Satellite-im/Uplink/assets/34157027/a437a5ec-390e-452d-8060-9081fb93f18e">

when calling:
<img width="944" alt="Screenshot 2023-08-28 at 17 46 35" src="https://github.com/Satellite-im/Uplink/assets/34157027/6a45b087-4c39-4932-bf7f-e83183af06fc">
<img width="874" alt="Screenshot 2023-08-28 at 17 46 42" src="https://github.com/Satellite-im/Uplink/assets/34157027/25213bb1-f5fb-4944-bca5-e0e575dcab82">
<img width="936" alt="Screenshot 2023-08-28 at 17 46 55" src="https://github.com/Satellite-im/Uplink/assets/34157027/b631e7f1-02f0-4319-aa80-79395506b255">
<img width="931" alt="Screenshot 2023-08-28 at 17 47 00" src="https://github.com/Satellite-im/Uplink/assets/34157027/9414dcfb-0e70-4e29-b566-16531ad4235e">

2023-08-28 16:13 UTC, sdwoodbury commented
@Flemmli97 I think I tested wrong. The screenshots I showed where it didn't work involved a group call instead of a direct call. When I used direct calls, the UI was the same after both sides joined the call. 

On the bright side, now we know that the UI for group calls hasn't been updated yet :grin:

2023-08-28 16:34 UTC, Flemmli97 commented
seems to be the same for groups too for me hmm

2023-08-29 15:33 UTC, Flemmli97 commented
@sdwoodbury asking again here for the above

2023-09-01 17:59 UTC, phillsatellite approved these changes

2023-09-01 19:38 UTC, sdwoodbury requested changes

2023-09-01 19:38 UTC, sdwoodbury commented on common/src/state/mod.rs
> +                    // Also remove the recipient from the active call if present
if we do this, we should also remove the participant from all pending calls.

also, and more importantly, this won't actually boot the person from the call, just from the UI. @stavares843 Blink would need a new feature to boot someone from a call. I think that if we really want this, we should make a separate ticket for it and add the support to Blink first.

2023-09-01 19:38 UTC, sdwoodbury commented on ui/src/components/media/calling.rs
> +                // TODO: we need to add an icon for this `if state.read().ui.silenced { Icon::Microphone } else { Icon::Microphone }`
the TODO has been addressed. can delete it now.

2023-09-01 21:30 UTC, InfamousVague commented
> > if you go to a group where is only 1 person > call > no avatar appears
> > ![image](https://user-images.githubusercontent.com/29093946/263120798-15159fd8-8499-4e7d-9813-aef5f337a7ed.png)
> > macOS, m1
> 
> yes cause it displays all members in the call except oneself

Maybe we can just display "Nobody is here" or "You're all alone"

2023-09-02 10:52 UTC, stavares843 commented
> Maybe we can just display "Nobody is here" or "You're all alone"


good idea 🔨

2023-09-06 14:35 UTC, stavares843 commented
missing addressing stu requested changes 🔨

2023-09-06 16:29 UTC, sdwoodbury commented
@Flemmli97  I still think that removing someone from a group shouldn't remove them from the call UI at this time because it wouldn't remove them from the call. Is this OK with @stavares843?

2023-09-06 16:30 UTC, stavares843 commented
if we can't remove from the call, not much point in just removing from the UI then

2023-09-06 16:56 UTC, Flemmli97 commented
should i just for now comment out that part so we can just uncomment it later? or delete it

2023-09-06 17:45 UTC, sdwoodbury commented
> should i just for now comment out that part so we can just uncomment it later? or delete it

Comment it out

2023-09-06 20:45 UTC, phillsatellite approved these changes

2023-09-06 20:46 UTC, phillsatellite commented
Functionality seems good when tested across Linux/Mac/Windows

2023-09-06 20:55 UTC, stavares843 approved these changes

2023-09-07 03:09 UTC, sdwoodbury approved these changes

2023-09-07 03:09 UTC, merged