feat(settings): Add device selection for microphone/speaker
Satellite-im/Uplink pull request #1202
Opened 2023-09-08 16:01 UTC by Flemmli97

### What this PR does 📖

- Adds ability to select microphones/speaker devices from audio settings

### Which issue(s) this PR fixes 🔨

- Resolve #1174

2023-09-08 17:46 UTC, lgmarchi requested changes
LGTM. Just fix some texts in the PR and 2 unwrap() code.

2023-09-08 17:46 UTC, lgmarchi commented on common/src/warp_runner/manager/commands/blink_commands.rs
> +    #[display(fmt = "GetAllMicrophones")]
Display Here should be `SetMicrophone`

2023-09-08 17:46 UTC, lgmarchi commented on common/src/warp_runner/manager/commands/blink_commands.rs
> +    #[display(fmt = "GetAllMicrophones")]
Display Here should be `GetAllSpeakers`

2023-09-08 17:46 UTC, lgmarchi commented on common/src/warp_runner/manager/commands/blink_commands.rs
> +    #[display(fmt = "GetAllMicrophones")]
Display Here should be `SetSpeaker`

2023-09-08 17:46 UTC, lgmarchi commented on ui/src/components/settings/sub_pages/audio.rs
> +                                *input_devices.write() = res.0.unwrap();
Should not be better to use `unwrap_or_default()` here?

2023-09-08 17:46 UTC, lgmarchi commented on ui/src/components/settings/sub_pages/audio.rs
> +                                log::error!("warp_runner failed to set output device: {e}");
Error here should be input device in the log

2023-09-11 13:33 UTC, sdwoodbury approved these changes
this looks fine. Note that there's a branch in Warp called `feat/audio-test` which will allow the user to test the speaker/microphone setup before finalizing the audio configuration. The Blink API will change slightly. 

I suspect that eventually, we won't want to apply the configuration changes until the user navigates away from this page but that will depend on whatever UI Kevin designs.

2023-09-11 13:33 UTC, sdwoodbury commented on common/src/warp_runner/manager/commands/blink_commands.rs
> +type DeviceResult = (
I recommend changing this to a struct with fields `available_devices` and `selected_device`. Eliminating the tuple would result in one less thing to memorize.

2023-09-11 13:33 UTC, sdwoodbury commented on ui/src/components/settings/sub_pages/audio.rs
> +                    initial_value: state.read().settings.input_device.as_ref().cloned().unwrap_or("Default".into()),
`Default` should probably be `default`. I hope it doesn't vary by platform. I have some changes planned for Blink to use a separate code path when the device name is "default"/"Default"

2023-09-13 15:21 UTC, lgmarchi approved these changes
LGTM.

2023-09-13 16:02 UTC, stavares843 requested changes
very neat 🎉 

something i noticed is

i have a macbook pro
then i connected by exterior headphones and the beats phones as well

when i deactivate them and no longer are connected to my macbook pro they still appear listed in uplink

<img width="918" alt="Captura de ecrã 2023-09-13, às 17 00 59" src="https://github.com/Satellite-im/Uplink/assets/29093946/c058e96b-b24c-483c-8c8b-559778b824ab">
<img width="912" alt="Captura de ecrã 2023-09-13, às 17 01 06" src="https://github.com/Satellite-im/Uplink/assets/29093946/1126f598-1acf-43d4-9727-517121ae2766">

2023-09-13 16:08 UTC, Flemmli97 commented
> very neat 🎉
> 
> something i noticed is
> 
> i have a macbook pro then i connected by exterior headphones and the beats phones as well
> 
> when i deactivate them and no longer are connected to my macbook pro they still appear listed in uplink
> 
> <img alt="Captura de ecrã 2023-09-13, às 17 00 59" width="918" src="https://user-images.githubusercontent.com/29093946/267717195-c058e96b-b24c-483c-8c8b-559778b824ab.png"> <img alt="Captura de ecrã 2023-09-13, às 17 01 06" width="912" src="https://user-images.githubusercontent.com/29093946/267717206-1126f598-1acf-43d4-9727-517121ae2766.png">

did you refresh the page? aka go to another page and back? or did you do it while on the settings page?

2023-09-13 17:23 UTC, stavares843 commented
> did you do it while on the settings page?

while in the settings page yes

2023-09-14 16:14 UTC, sdwoodbury commented
`cpal` doesn't provide callbacks when a device is disconnected. Blink only emits an event if there's an ongoing call and the audio device is disconnected because that results in an error. I think the best we can do is call blink's `get_available_microphones/speakers` functions every few seconds while this page is open to update the list.

2023-09-15 12:38 UTC, stavares843 approved these changes

2023-09-15 12:38 UTC, merged