chore(cargo): Update dependency
Satellite-im/Uplink pull request #1226
Opened 2023-09-20 15:24 UTC by dariusc93

### What this PR does 📖

- Simplify discovery, reducing logic 
- Remove nat status check and allow relay to be enabled regardless of port forwarding status
- Introduce a secondary discovery flag
- Refactored Blink interface, removing codec from `Blink::offer_call` and added `Blink::get_audio_device_config`

### Which issue(s) this PR fixes 🔨

- N/A

### Special notes for reviewers 🗒️
- Though not perfect, connectivity status should have improve compared to before.

### Additional comments 🎤
- Discovery has a secondary point (which is disabled by default) for discovering peers outside of DHT or direct connection, which would reduce cpu and memory consumption, however this will be refactored in the very near future

2023-09-20 22:24 UTC, phillsatellite approved these changes

2023-09-21 01:35 UTC, sdwoodbury requested changes
everything else looks good. just that one file needs to be deleted.

2023-09-21 01:35 UTC, sdwoodbury commented on ui/src/components/chat/compose/mod.rs
this file shouldn't exist anymore

2023-09-21 15:48 UTC, sdwoodbury approved these changes

2023-09-21 15:49 UTC, merged