fix(chatbar): unintnetional sends
Satellite-im/Uplink pull request #1316
Opened 2023-10-11 20:07 UTC by sdwoodbury

### What this PR does 📖

-  when typing fast, i get caught up because in uplink, the enter key works on keyup instead of on keydown. This PR makes the enter key work on keydown. Hopefully this results in a nicer typing experience. 

testing:
-  It should prevent extra sends resulting from holding down the enter key. 
- It should allow one to enter a  newline in a message and release the shift key before the enter key, and not send the message. 
- this should work with the left and right shift keys and the enter key and numpad enter key. 
- the arrow key functionality should be unaffected. 

### Which issue(s) this PR fixes 🔨

- Resolve #1315

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-10-11 21:22 UTC, dariusc93 approved these changes

2023-10-12 21:16 UTC, stavares843 requested changes
this PR

https://github.com/Satellite-im/Uplink/assets/29093946/c2bd1a0e-3e5b-43b5-a16c-48a85893cef9

dev

https://github.com/Satellite-im/Uplink/assets/29093946/9055acf5-2cb5-4474-99b1-b80e324535fa

flow
- go to chat
- write 4 lines for example
- go to second line and do a paragraph
- in this PR goes to line 2 to latest, in dev goes to line 2 to line 3 which is the expected behavior

2023-10-13 14:39 UTC, sdwoodbury commented
@stavares843  good job on finding something. should be fixed now.

2023-10-13 15:24 UTC, stavares843 approved these changes

2023-10-13 16:21 UTC, merged