update(SuggestedEmoji): Improve Suggested Emoji UI
Satellite-im/Uplink pull request #1548
Opened 2023-11-27 14:58 UTC by lgmarchi

### What this PR does 📖
### 1. Improve UI in Suggested Emoji 
<img width="663" alt="image" src="https://github.com/Satellite-im/Uplink/assets/63157656/f9a5674f-6491-45b7-8f67-dbe291131122">

### Which issue(s) this PR fixes 🔨

- Resolve #1545 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-11-27 16:33 UTC, sdwoodbury approved these changes

2023-11-27 16:34 UTC, dariusc93 approved these changes

2023-11-27 18:48 UTC, InfamousVague requested changes
Some small CSS things might need work, I can help tidy them up a bit if needed

2023-11-27 18:48 UTC, InfamousVague commented on ui/src/layouts/chats/style.scss
> +    top: var(--gap);
I think we will want `gap-less` here

2023-11-27 18:48 UTC, InfamousVague commented on ui/src/layouts/chats/style.scss
> +    right: var(--gap);
same here

2023-11-27 18:56 UTC, phillsatellite commented
Noticed a few small issues 

- It looks like the emoji selection box doesn't come out as far as the mockup UI does 

<img width="351" alt="Screenshot 2023-11-27 at 1 42 05 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/babb016a-6395-44d0-be9d-e4c7a6103d4d">

<img width="176" alt="Screenshot 2023-11-27 at 1 42 13 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/afdaac98-b51d-4387-86ae-cb2d430fb328">

(emoji selection box) 
<img width="698" alt="Screenshot 2023-11-27 at 1 45 15 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/00b64083-63ab-4f6b-b0a4-9ae1f1f1e6d3">

(reply modal)
<img width="691" alt="Screenshot 2023-11-27 at 1 45 56 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/9ac0bef2-ea08-4058-be58-101d5ca0543f">

Also noticed the X button was a little off and intruded into the highlight bar (@XileHorizon is working to see if he wants to modify the design a little for this part)
<img width="622" alt="Screenshot_2023-11-27_at_1 25 03_PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/7c96d002-c1c0-426a-9f09-1d177b9b0642">

2023-11-27 20:44 UTC, InfamousVague commented
<img width="936" alt="image" src="https://github.com/Satellite-im/Uplink/assets/1770198/0d5426d2-39d6-4316-9cbb-fca219e2aa2f">

2023-11-27 20:45 UTC, InfamousVague approved these changes

2023-11-27 23:48 UTC, phillsatellite approved these changes

2023-11-28 00:33 UTC, stavares843 approved these changes

2023-11-28 14:31 UTC, merged