improv(badge): Make badges consistent and circle like
Satellite-im/Uplink pull request #1627
Opened 2023-12-13 18:17 UTC by Flemmli97

### What this PR does 📖

- Makes notification badges (unreads, friends) consistent and circle stretching. As in it will stretch horizontally for larger numbers

### Which issue(s) this PR fixes 🔨

- Resolve #1624

2023-12-14 14:37 UTC, sdwoodbury requested changes
it looks like I can no longer right click on the chats icon to clear all unreads. I suspect we still want that context menu. 

![image](https://github.com/Satellite-im/Uplink/assets/8636602/6c8b7534-00b6-4511-915b-2364cd4230e5)

2023-12-15 14:29 UTC, Flemmli97 commented
> it looks like I can no longer right click on the chats icon to clear all unreads. I suspect we still want that context menu.
> 
> ![image](https://private-user-images.githubusercontent.com/8636602/290551572-6c8b7534-00b6-4511-915b-2364cd4230e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTA3OTIsIm5iZiI6MTcwMjY1MDQ5MiwicGF0aCI6Ii84NjM2NjAyLzI5MDU1MTU3Mi02YzhiNzUzNC0wMGI2LTQ1MTEtOTE1Yi0yMzY0Y2Q0MjMwZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTQyODEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNjMjIyMDlkZjZkYmY4MjliMGNmZTVmM2Y4NDFkNGU5NzE0MTRkM2FjMzllYzFmMDQ0OWNmNjM4OTRmM2EzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IGz30QtsHZsCvzIFz9yQvQjZSJGNhoHzLs7chLLsmLA)

fixed

2023-12-15 17:38 UTC, phillsatellite approved these changes

2023-12-15 18:01 UTC, sdwoodbury approved these changes

2023-12-15 18:55 UTC, merged