feat(chat): Chatbar markdown preview
Satellite-im/Uplink pull request #1705
Opened 2024-01-12 20:26 UTC by Flemmli97

### What this PR does 📖

- Adds markdown preview to the chatbar and editing textarea
- Uses this js library which is a wrapper around the codemirror js lib:
https://github.com/Flemmli97/markdown-editor

### Which issue(s) this PR fixes 🔨

- Resolve #1367

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-01-16 17:28 UTC, phillsatellite commented
@Flemmli97 Hey Kevin! I had some issues trying to get the markdown to appear in the chatbar on any of the OS's 

https://github.com/Satellite-im/Uplink/assets/93608357/16afc3a0-f175-4d3e-b803-136de570262e

2024-01-17 19:30 UTC, Flemmli97 commented
fixed

2024-01-17 22:45 UTC, stavares843 requested changes
in dev sending this works

```## Escaping Characters

To display a literal asterisk \* or underscore \_ in Markdown, use a backslash \ before the character.``` 

<img width="861" alt="Captura de ecrã 2024-01-17, às 22 43 44" src="https://github.com/Satellite-im/Uplink/assets/29093946/41135c30-7703-4820-b24b-50873e981c6e">


but on this branch does not work and returns the following error on the log

<img width="877" alt="Captura de ecrã 2024-01-17, às 22 44 41" src="https://github.com/Satellite-im/Uplink/assets/29093946/8229c96b-9282-4ff9-b1ed-d316c752dd1d">


i can copy paste but i cant sent it and also says 0/1024 on the chars, and the send button does not work

<img width="949" alt="Captura de ecrã 2024-01-17, às 22 41 52" src="https://github.com/Satellite-im/Uplink/assets/29093946/86371898-e17e-469c-9280-38fe54e4d39c">

2024-01-17 22:50 UTC, luisecm commented
Looking at the automated test results:

1. The following test "Favorites - Open Chat conversations with multiple users on Sidebar - Chat User B" is failing because test runner is failing due to timeout after retrying to type on Chat Screen - Text input field. Test runner is typing the text "Testing" but the value assigned to input field is "Testing " (one extra space added).  Is this extra space something we should keep?
![image](https://github.com/Satellite-im/Uplink/assets/35935591/328fcacc-c209-4c9d-9930-6ac31217a86b)

I am not sure if it is related to the following line 419 on kit/src/elements/textarea/mod.rs] file:
![image](https://github.com/Satellite-im/Uplink/assets/35935591/7a7fdfe0-a578-4686-a2ca-e19d1fd4ecbb)

2. The following test "Input Bar - Chars Counter on Input Bar displays 0/1024 before typing a text" is failing because the UI locator for inputCharMaxText is being modified in the DOM tree (I see a new text element "Selection deleted", which is moving the existing UI locators used on tests). This is something I can quickly fix when this PR is merged.
![image](https://github.com/Satellite-im/Uplink/assets/35935591/246b18ba-c0fe-468e-8940-0e38bf084ed9)

2024-01-17 23:14 UTC, stavares843 commented
thanks @luisecm 🔨

2024-01-17 23:16 UTC, stavares843 commented
btw @Flemmli97 another char where it happens the previous comment as well


```
$ \scriptsize{\text{alert('XSS Attack')}} $
```

<img width="943" alt="Captura de ecrã 2024-01-17, às 23 15 14" src="https://github.com/Satellite-im/Uplink/assets/29093946/b0ee7680-f73b-413c-bc7d-7edef122b747">

2024-01-18 15:03 UTC, Flemmli97 commented
> Looking at the automated test results:
> 
> 1. The following test "Favorites - Open Chat conversations with multiple users on Sidebar - Chat User B" is failing because test runner is failing due to timeout after retrying to type on Chat Screen - Text input field. Test runner is typing the text "Testing" but the value assigned to input field is "Testing " (one extra space added).  Is this extra space something we should keep?
>    ![image](https://private-user-images.githubusercontent.com/35935591/297538871-328fcacc-c209-4c9d-9930-6ac31217a86b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzg4NzEtMzI4ZmNhY2MtYzIwOS00YzlkLTk5MzAtNmFjMzEyMTdhODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGY1ZGIwODZiYTczNzM2Y2YwZTc2Y2YzYzc5ZmE5YmRjYmIxMjQ3N2Y1YWI0MTMzZDJjMTkzYzk1MzU0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zGGRflU3wgmjnHmGrHlp0iXVOK8wqG5wW8JzgK7wNKE)
> 
> I am not sure if it is related to the following line 419 on kit/src/elements/textarea/mod.rs] file: ![image](https://private-user-images.githubusercontent.com/35935591/297539915-7a7fdfe0-a578-4686-a2ca-e19d1fd4ecbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzk5MTUtN2E3ZmRmZTAtYTU3OC00Njg2LWEyY2EtZTE5ZDFmZDRlY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTk2OWNhODdhYmQ5MGQ0NzE3OWMyMzkxM2U1MGY2MjMxYTkyMTA4YTE2MDJjZWY2ZDNkNWEwYjFlMzIyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uq7zgFJVWjTJpgJXiUxQ6xlf9wDJqMQJj40t21uCi6w)
> 
> 2. The following test "Input Bar - Chars Counter on Input Bar displays 0/1024 before typing a text" is failing because the UI locator for inputCharMaxText is being modified in the DOM tree (I see a new text element "Selection deleted", which is moving the existing UI locators used on tests). This is something I can quickly fix when this PR is merged.
>    ![image](https://private-user-images.githubusercontent.com/35935591/297540858-246b18ba-c0fe-468e-8940-0e38bf084ed9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1NDA4NTgtMjQ2YjE4YmEtYzBmZS00NjhlLTg5NDAtMGUzOGJmMDg0ZWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MjVjZGM5M2M1NTZjN2I2ZTdiNzI1ZDhiZTBjN2ZkMTE0MWViYjVmMzRhOWI4Mzg3Yjc4MTFiZDAxYjdkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rg4YXw6W9fzXqg3ok8x3NRXFfGu9TOgYqju6Kwz9Rx8)

hmm idk why there is a whitespace. testing it in the app and looking at the dom there is no whitespace added there

2024-01-18 20:33 UTC, luisecm commented
> > Looking at the automated test results:
> > 
> > 1. The following test "Favorites - Open Chat conversations with multiple users on Sidebar - Chat User B" is failing because test runner is failing due to timeout after retrying to type on Chat Screen - Text input field. Test runner is typing the text "Testing" but the value assigned to input field is "Testing " (one extra space added).  Is this extra space something we should keep?
> >    ![image](https://private-user-images.githubusercontent.com/35935591/297538871-328fcacc-c209-4c9d-9930-6ac31217a86b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzg4NzEtMzI4ZmNhY2MtYzIwOS00YzlkLTk5MzAtNmFjMzEyMTdhODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGY1ZGIwODZiYTczNzM2Y2YwZTc2Y2YzYzc5ZmE5YmRjYmIxMjQ3N2Y1YWI0MTMzZDJjMTkzYzk1MzU0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zGGRflU3wgmjnHmGrHlp0iXVOK8wqG5wW8JzgK7wNKE)
> > 
> > I am not sure if it is related to the following line 419 on kit/src/elements/textarea/mod.rs] file: ![image](https://private-user-images.githubusercontent.com/35935591/297539915-7a7fdfe0-a578-4686-a2ca-e19d1fd4ecbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzk5MTUtN2E3ZmRmZTAtYTU3OC00Njg2LWEyY2EtZTE5ZDFmZDRlY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTk2OWNhODdhYmQ5MGQ0NzE3OWMyMzkxM2U1MGY2MjMxYTkyMTA4YTE2MDJjZWY2ZDNkNWEwYjFlMzIyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uq7zgFJVWjTJpgJXiUxQ6xlf9wDJqMQJj40t21uCi6w)
> > 
> > 2. The following test "Input Bar - Chars Counter on Input Bar displays 0/1024 before typing a text" is failing because the UI locator for inputCharMaxText is being modified in the DOM tree (I see a new text element "Selection deleted", which is moving the existing UI locators used on tests). This is something I can quickly fix when this PR is merged.
> >    ![image](https://private-user-images.githubusercontent.com/35935591/297540858-246b18ba-c0fe-468e-8940-0e38bf084ed9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1NDA4NTgtMjQ2YjE4YmEtYzBmZS00NjhlLTg5NDAtMGUzOGJmMDg0ZWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MjVjZGM5M2M1NTZjN2I2ZTdiNzI1ZDhiZTBjN2ZkMTE0MWViYjVmMzRhOWI4Mzg3Yjc4MTFiZDAxYjdkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rg4YXw6W9fzXqg3ok8x3NRXFfGu9TOgYqju6Kwz9Rx8)
> 
> hmm idk why there is a whitespace. testing it in the app and looking at the dom there is no whitespace added there

I already added one PR on the testing repo that addresses the changes required, you can see the status of tests execution on here: https://github.com/Satellite-im/testing-uplink/pull/606

2024-01-18 22:31 UTC, Flemmli97 commented
> > > Looking at the automated test results:
> > > 
> > > 1. The following test "Favorites - Open Chat conversations with multiple users on Sidebar - Chat User B" is failing because test runner is failing due to timeout after retrying to type on Chat Screen - Text input field. Test runner is typing the text "Testing" but the value assigned to input field is "Testing " (one extra space added).  Is this extra space something we should keep?
> > >    ![image](https://private-user-images.githubusercontent.com/35935591/297538871-328fcacc-c209-4c9d-9930-6ac31217a86b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzg4NzEtMzI4ZmNhY2MtYzIwOS00YzlkLTk5MzAtNmFjMzEyMTdhODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGY1ZGIwODZiYTczNzM2Y2YwZTc2Y2YzYzc5ZmE5YmRjYmIxMjQ3N2Y1YWI0MTMzZDJjMTkzYzk1MzU0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zGGRflU3wgmjnHmGrHlp0iXVOK8wqG5wW8JzgK7wNKE)
> > > 
> > > I am not sure if it is related to the following line 419 on kit/src/elements/textarea/mod.rs] file: ![image](https://private-user-images.githubusercontent.com/35935591/297539915-7a7fdfe0-a578-4686-a2ca-e19d1fd4ecbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzk5MTUtN2E3ZmRmZTAtYTU3OC00Njg2LWEyY2EtZTE5ZDFmZDRlY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTk2OWNhODdhYmQ5MGQ0NzE3OWMyMzkxM2U1MGY2MjMxYTkyMTA4YTE2MDJjZWY2ZDNkNWEwYjFlMzIyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uq7zgFJVWjTJpgJXiUxQ6xlf9wDJqMQJj40t21uCi6w)
> > > 
> > > 2. The following test "Input Bar - Chars Counter on Input Bar displays 0/1024 before typing a text" is failing because the UI locator for inputCharMaxText is being modified in the DOM tree (I see a new text element "Selection deleted", which is moving the existing UI locators used on tests). This is something I can quickly fix when this PR is merged.
> > >    ![image](https://private-user-images.githubusercontent.com/35935591/297540858-246b18ba-c0fe-468e-8940-0e38bf084ed9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1NDA4NTgtMjQ2YjE4YmEtYzBmZS00NjhlLTg5NDAtMGUzOGJmMDg0ZWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MjVjZGM5M2M1NTZjN2I2ZTdiNzI1ZDhiZTBjN2ZkMTE0MWViYjVmMzRhOWI4Mzg3Yjc4MTFiZDAxYjdkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rg4YXw6W9fzXqg3ok8x3NRXFfGu9TOgYqju6Kwz9Rx8)
> > 
> > 
> > hmm idk why there is a whitespace. testing it in the app and looking at the dom there is no whitespace added there
> 
> I already added one PR on the testing repo that addresses the changes required, you can see the status of tests execution on here: [Satellite-im/testing-uplink#606](https://github.com/Satellite-im/testing-uplink/pull/606)

does that address both points or only the 2.?

2024-01-18 22:45 UTC, luisecm commented
> > > > Looking at the automated test results:
> > > > 
> > > > 1. The following test "Favorites - Open Chat conversations with multiple users on Sidebar - Chat User B" is failing because test runner is failing due to timeout after retrying to type on Chat Screen - Text input field. Test runner is typing the text "Testing" but the value assigned to input field is "Testing " (one extra space added).  Is this extra space something we should keep?
> > > >    ![image](https://private-user-images.githubusercontent.com/35935591/297538871-328fcacc-c209-4c9d-9930-6ac31217a86b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzg4NzEtMzI4ZmNhY2MtYzIwOS00YzlkLTk5MzAtNmFjMzEyMTdhODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGY1ZGIwODZiYTczNzM2Y2YwZTc2Y2YzYzc5ZmE5YmRjYmIxMjQ3N2Y1YWI0MTMzZDJjMTkzYzk1MzU0ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zGGRflU3wgmjnHmGrHlp0iXVOK8wqG5wW8JzgK7wNKE)
> > > > 
> > > > I am not sure if it is related to the following line 419 on kit/src/elements/textarea/mod.rs] file: ![image](https://private-user-images.githubusercontent.com/35935591/297539915-7a7fdfe0-a578-4686-a2ca-e19d1fd4ecbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1Mzk5MTUtN2E3ZmRmZTAtYTU3OC00Njg2LWEyY2EtZTE5ZDFmZDRlY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTk2OWNhODdhYmQ5MGQ0NzE3OWMyMzkxM2U1MGY2MjMxYTkyMTA4YTE2MDJjZWY2ZDNkNWEwYjFlMzIyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uq7zgFJVWjTJpgJXiUxQ6xlf9wDJqMQJj40t21uCi6w)
> > > > 
> > > > 2. The following test "Input Bar - Chars Counter on Input Bar displays 0/1024 before typing a text" is failing because the UI locator for inputCharMaxText is being modified in the DOM tree (I see a new text element "Selection deleted", which is moving the existing UI locators used on tests). This is something I can quickly fix when this PR is merged.
> > > >    ![image](https://private-user-images.githubusercontent.com/35935591/297540858-246b18ba-c0fe-468e-8940-0e38bf084ed9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU5MTUsIm5iZiI6MTcwNTU4NTYxNSwicGF0aCI6Ii8zNTkzNTU5MS8yOTc1NDA4NTgtMjQ2YjE4YmEtYzBmZS00NjhlLTg5NDAtMGUzOGJmMDg0ZWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MjVjZGM5M2M1NTZjN2I2ZTdiNzI1ZDhiZTBjN2ZkMTE0MWViYjVmMzRhOWI4Mzg3Yjc4MTFiZDAxYjdkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rg4YXw6W9fzXqg3ok8x3NRXFfGu9TOgYqju6Kwz9Rx8)
> > > 
> > > 
> > > hmm idk why there is a whitespace. testing it in the app and looking at the dom there is no whitespace added there
> > 
> > 
> > I already added one PR on the testing repo that addresses the changes required, you can see the status of tests execution on here: [Satellite-im/testing-uplink#606](https://github.com/Satellite-im/testing-uplink/pull/606)
> 
> does that address both points or only the 2.?

It's addressing both points. Since I did not find any visible issue while testing your PR and point #1 could be something Dioxus related, I went ahead and added an update to the tests that will take care of it

2024-01-19 14:48 UTC, stavares843 commented
when sending this

```
> This is a blockquote.
> It can span multiple lines.
```


it sends fine

<img width="763" alt="Captura de ecrã 2024-01-19, às 14 47 30" src="https://github.com/Satellite-im/Uplink/assets/29093946/fab94f8e-8acb-41ac-8dbc-76a17f5a206b">


but the preview appears like this

<img width="778" alt="Captura de ecrã 2024-01-19, às 14 47 41" src="https://github.com/Satellite-im/Uplink/assets/29093946/53882e6b-4ed2-4f45-8f98-577b0dfaa859">


the first line is the same as the second in terms of content but layout wise is different


macOS, m1

2024-01-19 16:37 UTC, Flemmli97 commented
fixed

2024-01-19 19:04 UTC, stavares843 approved these changes

2024-01-19 19:08 UTC, Flemmli97 commented
before mergine will look into #1737 first

2024-01-19 19:11 UTC, stavares843 commented
sounds good 🔨

2024-01-22 14:42 UTC, Flemmli97 commented
should fix that now

2024-01-22 20:21 UTC, stavares843 commented
thanks 🎉

2024-01-22 20:22 UTC, stavares843 commented on kit/src/elements/textarea/mod.rs
> +                                log::debug!("paste");
do we need the log?

2024-01-22 20:22 UTC, stavares843 commented on kit/src/elements/textarea/mod.rs
> +                        log::debug!("val {val}");
do we need the log?

2024-01-24 16:45 UTC, dariusc93 approved these changes

2024-01-24 16:47 UTC, merged