update(Files): Add Preview for PDF and Code Files
Satellite-im/Uplink pull request #1825
Opened 2024-02-05 18:02 UTC by lgmarchi

### What this PR does 📖
### 1. Changed Icons on files, now files that are docs, excel, ppt, language codes will have different icons and unknown files. 
![image](https://github.com/Satellite-im/Uplink/assets/63157656/3a52001a-5d1b-4f32-9c28-23c5e7c4fe73)

### 3. Possible to preview PDF files 

https://github.com/Satellite-im/Uplink/assets/63157656/617346ef-4604-46bb-9d9c-e738254ce4b7

### 4. Possible to preview Language Code files 

https://github.com/Satellite-im/Uplink/assets/63157656/bacbd8bd-9f9a-48a2-bf46-c851ca7304db

### 5. Remove ogg from audio files and change audio layout on preview 

![Screenshot 2024-02-06 at 11 17 15](https://github.com/Satellite-im/Uplink/assets/63157656/99f87523-93b2-4b26-bd11-33cfcc394222)

### Which issue(s) this PR fixes 🔨

- Resolve #1801 
- Resolve #1826 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-02-05 20:40 UTC, phillsatellite commented
DM'd Lucas with a small issue I found. I noticed I could preview code language files in File Storage but not in chats. He said he is going to make a new commit for that 👍 

https://github.com/Satellite-im/Uplink/assets/93608357/ebd8d63b-d107-419e-8516-ab9e7589f0e7

2024-02-05 21:25 UTC, dariusc93 commented on ui/src/layouts/storage/files_layout/file_preview.rs
> +
We can simplify this logic to something like the following

```suggestion
let code_content = is_code
        .then(|| std::fs::read_to_string(file_path_in_local_disk.read().clone()).ok())
        .flatten()
        .unwrap_or_default();

```

2024-02-05 21:25 UTC, dariusc93 commented on ui/src/layouts/storage/files_layout/file_preview.rs
> +        .unwrap_or("");
```suggestion
        .unwrap_or_default();
```

2024-02-05 22:29 UTC, phillsatellite commented
@lgmarchi Just one other thing (maybe we can get another Windows user to test this out) but when I open a pdf on Mac/Linux it opens fine with no issues but on Windows the file will open but with no content inside of preview. I tried to scroll up in Windows to see if maybe the content was just out of view but no luck 

MacOS: 
![image](https://github.com/Satellite-im/Uplink/assets/93608357/1a1abd69-1e8c-41a6-9e57-64ced755bc7b)

Windows: 
![image](https://github.com/Satellite-im/Uplink/assets/93608357/c6eabf6a-59d5-4fb3-a56b-f689c41b249c)

2024-02-06 13:19 UTC, lgmarchi commented
> @lgmarchi Just one other thing (maybe we can get another Windows user to test this out) but when I open a pdf on Mac/Linux it opens fine with no issues but on Windows the file will open but with no content inside of preview. I tried to scroll up in Windows to see if maybe the content was just out of view but no luck
> 
> MacOS: ![image](https://private-user-images.githubusercontent.com/93608357/302445782-1a1abd69-1e8c-41a6-9e57-64ced755bc7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2NjUsIm5iZiI6MTcwNzIyNTM2NSwicGF0aCI6Ii85MzYwODM1Ny8zMDI0NDU3ODItMWExYWJkNjktMWU4Yy00MWE2LTllNTctNjRjZWQ3NTViYzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMmM0ZGEwMjViMTBiZjRhODQ3NWQ0YzJmYzE3NTc3N2M1YTgyZjI5YzQ1NDg1NGM4OTEwZDBhMjM2MmJmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9_Pj7khHyD9PupV5PE1Yx286_5k_NNZlnskUehdB2k)
> 
> Windows: ![image](https://private-user-images.githubusercontent.com/93608357/302445821-c6eabf6a-59d5-4fb3-a56b-f689c41b249c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU2NjUsIm5iZiI6MTcwNzIyNTM2NSwicGF0aCI6Ii85MzYwODM1Ny8zMDI0NDU4MjEtYzZlYWJmNmEtNTlkNS00ZmIzLWE1NmItZjY4OWM0MWIyNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZGJkNmU2NTM4NGVmNjUyYmZlMzUwM2YyM2Q0MWNjZDA1YjExNTEzNjFkMDUyODZjYmU5MzQ5Njc5MjU0ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NyHuFZ3lvjoxCeZeX3Q1eSdaVECTXw7s6zByUYM7Iz4)

Interesting and very weird my friend. I will investigate.

2024-02-07 15:55 UTC, phillsatellite approved these changes

2024-02-07 18:12 UTC, dariusc93 commented on common/src/lib.rs
> +        FileType::Image
What if a file is not an image? Would it be better to have a generic type that would be the default?

2024-02-08 13:00 UTC, lgmarchi commented on common/src/lib.rs
> +        FileType::Image
Changed!

2024-02-08 14:56 UTC, dariusc93 approved these changes

2024-02-08 15:29 UTC, stavares843 reviewed
appears this icon when upload .gif for example

<img width="677" alt="Captura de ecrã 2024-02-08, às 15 27 32" src="https://github.com/Satellite-im/Uplink/assets/29093946/deb00a02-231b-45a8-abe2-f492cd5d9f94">

2024-02-08 15:30 UTC, stavares843 requested changes
when clicking on a image that was sent appears this


https://github.com/Satellite-im/Uplink/assets/29093946/1451e59f-f471-48f5-b7aa-a7e4d3aaea8a


macOS, m1

2024-02-08 15:33 UTC, phillsatellite commented
When testing after the latest commits, Ive also noticed that you have to click on a file a couple times to get the preview to open. On first attempt it will say "it is not possible to preview this file" then if you click it again after that file preview will open 

https://github.com/Satellite-im/Uplink/assets/93608357/8652de30-f19f-4821-9b0c-656f377d6cd5

2024-02-08 15:33 UTC, stavares843 commented
also i can open pdf's i sent fine but if i try to open any pdf's phil sent me does not open and no error appears

https://github.com/Satellite-im/Uplink/assets/29093946/ad0b7bf8-1544-4500-a55d-a107bbd6dbd2

<img width="752" alt="Captura de ecrã 2024-02-08, às 15 33 28" src="https://github.com/Satellite-im/Uplink/assets/29093946/edb03ca2-ecd8-49a1-a081-d7e5780c46bb">

2024-02-08 18:18 UTC, stavares843 approved these changes

2024-02-08 18:20 UTC, stavares843 approved these changes

2024-02-08 18:22 UTC, phillsatellite approved these changes

2024-02-08 18:23 UTC, merged