task(recovery): Redo seed enter recovery page
Satellite-im/Uplink pull request #1915
Opened 2024-03-08 16:58 UTC by Flemmli97

### What this PR does 📖

- Redo the seed recovery page. This PR changes the page to match the style of the other seed display pages.
  The phrases are now split into their own input. Typing enter will go to the next input unless the user is at the end where it will use act as the recovery button.
  Copy pasting an input with the phrases split into new lines will auto paste them into their correct places.
  E.g.
  ```
suspect
number
enemy
liar
estate
usual
state
total
dizzy
alley
eyebrow
spatial
```
Having too many or incomplete phrases will only paste the relevant bits in.

- This PR also makes copying the seed phrases easier by disabling selection on the seed number so the user can simply mouse drag select over the phrases to select them

### Which issue(s) this PR fixes 🔨

- Resolve #1720

2024-03-08 18:27 UTC, phillsatellite commented
Worked very well on MacOS but on Windows I noticed an issue (I had Sheldon verify that this happens on his side as well) when you paste your entire seed on Windows each phrase has \r behind it 

![image](https://github.com/Satellite-im/Uplink/assets/93608357/b4a9c0dc-15f8-42cf-82a4-edabfb47ebba)

2024-03-08 18:27 UTC, stavares843 approved these changes

2024-03-08 18:28 UTC, stavares843 requested changes
what phil mentioned above

2024-03-11 16:49 UTC, luisecm commented
@Flemmli97 Automated tests failures on import account tests are expected on this PR since there is a change in the info text from the screen and also the layout is changing. I will push the corresponding test updates for this screen once that this PR is merged
![image](https://github.com/Satellite-im/Uplink/assets/35935591/74dd4de0-c8e1-4aa3-bfb8-9ac16fd80a12)

2024-03-11 17:38 UTC, stavares843 commented
thanks @luisecm 🔨

2024-03-11 17:44 UTC, stavares843 commented
https://github.com/Satellite-im/Uplink/assets/29093946/cdafb7d3-deaf-4de7-a1f5-d6c9be9d9f38


if the seed is invalid, error appears as expected but the buttons are hidden unless you maximise the window

2024-03-11 17:45 UTC, stavares843 commented
https://github.com/Satellite-im/Uplink/assets/29093946/ede121b6-049d-4bcc-b11b-c9738cd98108


the toast is a bit cut off as well

2024-03-11 17:45 UTC, stavares843 commented
macOS, m1

2024-03-11 18:00 UTC, Flemmli97 commented
> @Flemmli97 Automated tests failures on import account tests are expected on this PR since there is a change in the info text from the screen and also the layout is changing. I will push the corresponding test updates for this screen once that this PR is merged ![image](https://private-user-images.githubusercontent.com/35935591/311790098-74dd4de0-c8e1-4aa3-bfb8-9ac16fd80a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODAyNDUsIm5iZiI6MTcxMDE3OTk0NSwicGF0aCI6Ii8zNTkzNTU5MS8zMTE3OTAwOTgtNzRkZDRkZTAtYzhlMS00YWEzLWJmYjgtOWFjMTZmZDgwYTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE3NTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZWU0NmI0ZTEwZDBkNmMwYjRkZTkzYzQ0OTFiYjAyODBiNTlhMmU4NWEyNThjZWY2YzhmYTlhNTQyZWUzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QfVmwu84ye5g7IRG3sd_ZZV2CFFtYe7OPvgDomYHy_8)

ye i updated a translation text too to better reflect what the user now has to do

2024-03-11 18:01 UTC, Flemmli97 commented
> Gravacao.do.ecra.2024-03-11.as.17.40.43.mov 
> 
> the toast is a bit cut off as well

hmm toast is supposed to look like that. but i guess it doesnt look too good

2024-03-11 18:19 UTC, stavares843 commented
yes i mean we can ignore the toast for now

is possible to add a scroll or to make the default window size bigger? because when the error appears the user does not see the buttons as they are hidden

cc @Flemmli97

2024-03-12 16:46 UTC, stavares843 approved these changes

2024-03-12 20:39 UTC, dariusc93 approved these changes

2024-03-12 22:57 UTC, merged