feat(ScrollPosition): Return scroll position
Satellite-im/Uplink pull request #192
Opened 2023-01-25 17:05 UTC by lgmarchi

### What this PR does 📖
### 1. Return Scroll position when in chat messages 

### 2. Onscroll function doesn't work on MacOS
- 

### Which issue(s) this PR fixes 🔨

- Resolve #178 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-01-26 00:56 UTC, InfamousVague commented
for this feature, what requirement are we hoping to use this for? I think we can do this without needing to add JS here

2023-01-26 16:36 UTC, lgmarchi commented
> for this feature, what requirement are we hoping to use this for? I think we can do this without needing to add JS here

Scrollposition will be necessary to do pagination

2023-01-27 04:30 UTC, InfamousVague requested changes
Let's wait a bit on this, I'm nervous this could lead to performance issues

2023-01-27 16:28 UTC, sdwoodbury commented
we could make this a draft and keep it on hand for later

2023-02-08 18:00 UTC, InfamousVague commented
Closing the PR, let's keep the branch in case we need it. No need to keep the PR open or in draft though.

2023-02-08 18:00 UTC, closed without merging