feat(Constellation): Start constellation in Uplink adding new folder
Satellite-im/Uplink pull request #212
Opened 2023-01-31 19:59 UTC by lgmarchi

### What this PR does 📖
### 1. Most part of code, is adding constellation on Uplink, following same pattern from Raygun and Multipass

### 2. 2 first functions from Constellation, is to get items from current directory and add new folder 
a. We can use mock data and add new folder just to UI, but it will lost data when we restart app 

https://user-images.githubusercontent.com/63157656/215869276-c3138011-177a-4cda-8c08-05a53769f07c.mov

b. We can use real data, adding new folder will upload this to FileSystem, and show it again when restart app

https://user-images.githubusercontent.com/63157656/215869094-9d461f49-77a7-46d0-8239-4452b98bf92a.mov

- 

### Which issue(s) this PR fixes 🔨

- Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-01-31 20:23 UTC, phillsatellite commented
Hi Lucas! Awesome step forward! Just a few things I found on here that I think would perfect it. If you want to fix these in a new PR just lemme know and I'll add some tickets for them! 

1. The name of the folder sits to the left when you save it, I think it might be nice to have the title of the folder appear centered. 

<img width="84" alt="Screenshot 2023-01-31 at 3 17 17 PM" src="https://user-images.githubusercontent.com/93608357/215873978-2577f778-dec0-4ccf-830c-6826958eff7f.png">

2. We might want to limit chars for the names of folders, right now User can add as many as theyd like and it will extend across the entire screen.

https://user-images.githubusercontent.com/93608357/215874158-8dc5be4e-4269-49ad-8b53-79edc1d5dd9b.mov

2023-01-31 21:18 UTC, sdwoodbury requested changes
good work! I suggested some small changes.

2023-01-31 21:18 UTC, sdwoodbury commented on kit/src/elements/folder/mod.rs
> +                            id: Uuid::new_v4().to_string(),
there might not be a need to generate a random id. without this, does the list of files not update? 
if it works without the `id` field, that field should be removed since we're not using the id to prevent re-renders

2023-01-31 21:18 UTC, sdwoodbury commented on ui/src/state/mod.rs
> +    pub items: items::Items,
i suggest picking a different name for items. i think storage would be more descriptive.  same thing for the file `state/items.rs` -> `state/storage.rs`

also, until there is data which persists, this field could be `#[serde(skip)]` so long as it implements `Default`

also, unrelated - further down `hooks` is `#[serde(skip_serializing, skip_deserializing)]`. i know this wasn't you. i thought I changed that to `#[serde(skip)]`, which i believe is equivalent. we may want to take this opportunity to change it back

2023-01-31 21:18 UTC, sdwoodbury commented on ui/src/state/items.rs
> +    pub all: Vec<warp::constellation::item::Item>,
I think that `all` may be unnecessary. it's only used in `join`, which could instead merge `self.directories` with `other.directories` and `self.files` with `other.files`. 

i looked closer at the `join` function for `chats` and `friends` and i believe it's now  unnecessary. it was useful at one time but should have been deleted. for example, `friends_init` defaults to true when mock data is enabled, causing that use_future would exit early, and `Friends::join` would never be called. 

it turns out that `Items::join` is also unnecessary.

2023-01-31 21:18 UTC, sdwoodbury commented on ui/src/layouts/files.rs
> +                        if STATIC_ARGS.use_mock {
to reduce nesting, i recommend handling the mock case for `AddNewFolder` outside of the `use_coroutine`

2023-01-31 21:18 UTC, sdwoodbury commented on ui/src/layouts/files.rs
> +                        if STATIC_ARGS.use_mock {
same

2023-01-31 21:18 UTC, sdwoodbury commented on ui/src/main.rs
> +                        logger::error(&e.to_string());
this works but we no longer need to do this. `log::error!("<some message> {}", e);` is now possible.

2023-01-31 21:18 UTC, sdwoodbury commented on ui/src/layouts/files.rs
> +                    if STATIC_ARGS.use_mock {
i'm fine with this but suspect that the mock data generation should instead go in the `testing/mock.rs` module

2023-02-01 04:09 UTC, dariusc93 reviewed
Left some comments and a question

2023-02-01 04:09 UTC, dariusc93 commented on ui/src/layouts/files.rs
> +                            let (tx, rx) = oneshot::channel::<Result<(), warp::error::Error>>();
Not a blocker but you usually dont need to define a type a head of time since the compiler would detect it when using it (eg `tx` is used in `rsp` field so it would detect the type that way).

2023-02-01 04:09 UTC, dariusc93 commented on ui/src/state/items.rs
> +pub struct Items {
Could you explain the need for `all` while also using `files` and `directories`? I wonder if some of the fields is necessary since in constellation, you can use `Directory` and get the list the items and resolve it into either a `File` or `Directory`. Containing a list of files, directories, and items may not be ideal since youre holding unnecessary data.

2023-02-01 04:09 UTC, dariusc93 commented on ui/src/warp_runner/manager/commands/constellation_commands.rs
> +    let mut directories: Vec<Directory> = Vec::new();
if `directories` and `files` are to be used, you could iterate over `items` by doing something along the lines of

```rust
let directories = items.iter().filter_map(|item| item.get_directory().ok()).collect::<Vec<_>>();
```

Same with `files`, although I do feel splitting them up like this is counterproductive and would retain unnecessary data if you are also holding onto `items` too.

2023-02-01 12:43 UTC, lgmarchi commented on kit/src/elements/folder/mod.rs
> +                            id: Uuid::new_v4().to_string(),
It is necessary, because when we open this field, there is a javascript code to focus on this input field, and for this, is necessary the id

2023-02-01 13:38 UTC, lgmarchi commented on ui/src/state/items.rs
> +    pub all: Vec<warp::constellation::item::Item>,
done

2023-02-01 13:39 UTC, lgmarchi commented on ui/src/state/items.rs
> +pub struct Items {
I would just let a vec with all items as well to maybe in the future, presentation of files and folders be different, but for now I will delete this field

2023-02-01 13:40 UTC, lgmarchi commented on ui/src/warp_runner/manager/commands/constellation_commands.rs
> +    let mut directories: Vec<Directory> = Vec::new();
Done!

2023-02-01 13:47 UTC, lgmarchi commented on ui/src/state/mod.rs
> +    pub items: items::Items,
Done!

2023-02-01 13:52 UTC, lgmarchi commented on ui/src/layouts/files.rs
> +                            let (tx, rx) = oneshot::channel::<Result<(), warp::error::Error>>();
It is asking to let type because of rx

2023-02-01 14:02 UTC, lgmarchi commented on ui/src/layouts/files.rs
> +                    if STATIC_ARGS.use_mock {
Done!

2023-02-01 14:03 UTC, lgmarchi commented
> Hi Lucas! Awesome step forward! Just a few things I found on here that I think would perfect it. If you want to fix these in a new PR just lemme know and I'll add some tickets for them!
> 
> 1. The name of the folder sits to the left when you save it, I think it might be nice to have the title of the folder appear centered.
> 
> <img alt="Screenshot 2023-01-31 at 3 17 17 PM" width="84" src="https://user-images.githubusercontent.com/93608357/215873978-2577f778-dec0-4ccf-830c-6826958eff7f.png">
> 
> 2. We might want to limit chars for the names of folders, right now User can add as many as theyd like and it will extend across the entire screen.
> 
>  Screen.Recording.2023-01-31.at.3.20.02.PM.mov

Phill, I changed to be 64 chars maximum, but folder name will be formatted to not over other names.

2023-02-01 14:36 UTC, sdwoodbury approved these changes
looks good to me. thanks for the changes!

2023-02-01 15:33 UTC, dariusc93 approved these changes
LTGM. Left a suggestion but its non-blocking

2023-02-01 15:33 UTC, dariusc93 commented on ui/src/layouts/storage.rs
> +        if STATIC_ARGS.use_mock == false {
```suggestion
        if !STATIC_ARGS.use_mock {
```

2023-02-01 16:11 UTC, phillsatellite approved these changes

2023-02-01 16:30 UTC, phillsatellite commented
Hi Lucas! I noticed something new when I was re-testing everything. When I was going to switch to mobile view I noticed that when you turn on Dev Mode all the folders will be missing, is this intended or a bug? 

https://user-images.githubusercontent.com/93608357/216103590-0e643f01-8c14-403f-acf8-27105b70a694.mov

2023-02-01 18:24 UTC, lgmarchi commented on ui/src/layouts/storage.rs
> +        if STATIC_ARGS.use_mock == false {
Man, I was thinking about this, is not more readable to use == false? 

I think it is easier to understand, I am not sure what way is better in good practices, i want your opinion too on this

2023-02-02 12:30 UTC, lgmarchi commented
> Hi Lucas! I noticed something new when I was re-testing everything. When I was going to switch to mobile view I noticed that when you turn on Dev Mode all the folders will be missing, is this intended or a bug?
> 
>  Screen.Recording.2023-02-01.at.11.28.30.AM.mov

I fixed bottom nav bar my friend!

2023-02-02 13:07 UTC, lgmarchi commented
> Hi

Fix folders missing when we update app.

2023-02-02 16:28 UTC, phillsatellite approved these changes

2023-02-02 16:29 UTC, phillsatellite commented
Put missing dev review for Lucas's most recent changes he added. Approved on my side 👍

2023-02-03 01:35 UTC, InfamousVague approved these changes

2023-02-03 01:35 UTC, InfamousVague commented on kit/src/elements/folder/mod.rs
> +    if folder_name_formatted.len() > 15 {
can we make this > 15 a FOLDER_LEN constant at the top of the file?

2023-02-03 01:35 UTC, InfamousVague commented on ui/src/layouts/storage.rs
> +
Is this file renamed to Storage for any specific reason or just matching warp? I'm okay with whatever just want to be consistent across the app.

2023-02-03 01:35 UTC, InfamousVague commented
LGTM after the mentioned comments

2023-02-03 13:10 UTC, lgmarchi commented on ui/src/layouts/storage.rs
> +
Is just to use better name than I was using before, but we can change for another as well without problems, like FilesBrowser

2023-02-03 13:34 UTC, lgmarchi commented on kit/src/elements/folder/mod.rs
> +    if folder_name_formatted.len() > 15 {
Absolutely!

2023-02-03 14:36 UTC, phillsatellite approved these changes

2023-02-03 14:39 UTC, merged