Add resize bindings for better "responsive" use cases.
Satellite-im/Uplink pull request #251
Opened 2023-02-04 06:37 UTC by InfamousVague

Also updates the focus state of the app when we click on and off. debugging issue with size not accurately updating.

2023-02-04 08:29 UTC, InfamousVague commented
This does not address anything in particular, rather it sets us up for the infamous "resize observer" we've been missing as well as a helpful `bool` representing weather or not the application is in focus or not which is super helpful for dispatching notifications.  I assume the issue with the resized size always being the same is an issue outside of the newly added code either in dioxus or wry.

2023-02-06 16:24 UTC, sdwoodbury commented on ui/src/components/settings/sidebar.rs
> +                        if state.read().configuration.config.audiovideo.interface_sounds {
this would be nicer if `configuration` has a function we could call instead of `configuration.config.audiovideo.interface_sounds`

2023-02-06 17:07 UTC, sdwoodbury requested changes
looks fine. i highly suggest either 
1) adding some convenience functions to the config struct
2)  not wrapping the `Configuration` from `src/config.rs` inside of the `Configuration` struct from `src/state/configuration.rs`. 

calling `state.read().configuration.config` feels redundant.

2023-02-06 17:12 UTC, InfamousVague commented on ui/src/components/settings/sidebar.rs
> +                        if state.read().configuration.config.audiovideo.interface_sounds {
Let's think over this a bit more in the future, down to refactor this but I don't know if this is the PR for that. This simply adds helpers into state for real time events.

2023-02-06 17:15 UTC, sdwoodbury approved these changes
approving and letting the change to `config` be handled in another PR.

2023-02-06 18:28 UTC, phillsatellite approved these changes

2023-02-06 18:29 UTC, merged

2023-02-06 21:48 UTC, WanderingHogan commented
@InfamousVague this merge makes the sidebar hide/only render when you make the screen much larger

![Screenshot 2023-02-06 at 2 48 31 PM](https://user-images.githubusercontent.com/2993032/217095538-3c184c9a-f8b2-4ad2-81ff-35f5fb124f17.png)
![Screenshot 2023-02-06 at 2 47 27 PM](https://user-images.githubusercontent.com/2993032/217095563-36d083d4-6c4e-4687-a554-b8a6c4527ab1.png)