chore(Sounds): Started wiring notifiation sounds
Satellite-im/Uplink pull request #276
Opened 2023-02-08 04:03 UTC by InfamousVague

### What this PR does 📖

- 

### Which issue(s) this PR fixes 🔨

- Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-02-08 19:47 UTC, InfamousVague commented
This is almost ready, there is just a remaining bug where the sound is played twice when not focusing the app, and for some reason it's played even when the new message is coming from the active chat

2023-02-08 19:56 UTC, InfamousVague commented
@phillsatellite this PR brings the ability to get notification sounds when you get a friend request and when messages come in.

2023-02-08 20:42 UTC, sdwoodbury requested changes

2023-02-08 20:42 UTC, sdwoodbury commented on ui/src/warp_runner/ui_adapter/message_event.rs
> +                    "New friend request!".into(),
needs translation

2023-02-08 20:42 UTC, sdwoodbury commented on ui/src/state/mod.rs
> +                        "New friend request!".into(),
needs translations

2023-02-08 20:42 UTC, sdwoodbury commented on ui/src/state/mod.rs
> +                        "New friend request!".into(),
same

2023-02-08 22:36 UTC, phillsatellite commented
@InfamousVague Yo! So I had a few issues,

This I replicated on both Windows and MacOS, it seems like _Message Sounds_ toggle is missing a click 
https://user-images.githubusercontent.com/93608357/217663577-b30cc504-a476-44ae-ada6-6165b9fdfbef.mov

The second issue @tooshel had on dev branch yesterday but I still havent been able to replicate on there. When I have a Windows User message a Mac User everytime the Mac User receives a message the text input box shoots to the top of the page

https://user-images.githubusercontent.com/93608357/217667045-b49334ae-f512-4066-a65f-1f98a6a2be6d.mov

2023-02-10 21:57 UTC, InfamousVague commented
> @InfamousVague Yo! So I had a few issues,
> 
> This I replicated on both Windows and MacOS, it seems like _Message Sounds_ toggle is missing a click https://user-images.githubusercontent.com/93608357/217663577-b30cc504-a476-44ae-ada6-6165b9fdfbef.mov
> 
> The second issue @tooshel had on dev branch yesterday but I still havent been able to replicate on there. When I have a Windows User message a Mac User everytime the Mac User receives a message the text input box shoots to the top of the page
> edit.mov

This could be related to line endings but I don't think it's related to this ticket since it just sends out the notification arbitrarily when we get the associated events. 

I will wire up the sound now though!

2023-02-10 22:03 UTC, InfamousVague commented
@phillsatellite should all be good to go now, I was able to hear the flip sound on my end but only in one direction but I did resolve a different bug around that area. If the thing doesn't make the sound twice for right now I wouldn't sweat it, we might just end up having to rethink some of the stuff in the sound util in the future if it becomes a problem.

2023-02-13 14:29 UTC, sdwoodbury requested changes, later dismissed
the requested change from last time wasn't addressed. only the English translation was added. Translations should be added for all languages in the `shared/locales` folder

2023-02-13 14:29 UTC, sdwoodbury commented on ui/src/state/configuration.rs
> +        let _ = self.config.save();
should only save if `status != self.config.audiovideo.message_sounds`

2023-02-14 06:51 UTC, InfamousVague commented
> the requested change from last time wasn't addressed. only the English translation was added. Translations should be added for all languages in the `shared/locales` folder

I don't think we should require this, it's a little outta scope and I want to avoid crappy google translate translations by non native speaking developers. It should fallback just fine to the english version pending proper translation.

2023-02-14 06:53 UTC, InfamousVague commented on ui/src/state/configuration.rs
> +        let _ = self.config.save();
Let's address this in a future PR as every configuration method currently doesn't use this logic and it's out of scope of this PR.

2023-02-14 15:25 UTC, sdwoodbury approved these changes
now it compiles

2023-02-15 21:03 UTC, merged