feat(chats): show unread
Satellite-im/Uplink pull request #313
Opened 2023-02-17 17:00 UTC by sdwoodbury

### What this PR does 📖

- what the title says

### Which issue(s) this PR fixes 🔨

- Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

![image](https://user-images.githubusercontent.com/8636602/219716315-9f82eb58-ed8f-437d-b602-4585abe65877.png)

2023-02-17 17:46 UTC, lgmarchi requested changes
It seems if you have just one friend, it not work.

Tested with a user on MacOS and a user on Windows! 


https://user-images.githubusercontent.com/63157656/219732904-7097e7d2-faea-4784-a54e-fbf1ca3aa244.mov

Or if user went out chat, with that conversation selected, and go to folders or friends for example: 


https://user-images.githubusercontent.com/63157656/219738419-be4505c5-98e9-46a6-bb4e-467424856319.mov

2023-02-17 21:43 UTC, phillsatellite approved these changes

2023-02-18 13:27 UTC, lgmarchi approved these changes
Working fine! Approved!

2023-02-18 13:31 UTC, dariusc93 approved these changes

2023-02-18 14:31 UTC, merged