fix(clearmessage): clear friend did after submit
Satellite-im/Uplink pull request #314
Opened 2023-02-20 18:13 UTC by Jekrimo

### What this PR does 📖

- clears input form after submit for both add button and input return

### Which issue(s) this PR fixes 🔨

- Resolve #

#304 

### Special notes for reviewers 🗒️

This also fixes a bug that our friend request wasn't being sent on enter

2023-02-20 19:31 UTC, dariusc93 reviewed
LGTM. Left a suggestion (though non-blocking) but something i think might be preferable to do would be to use `friend_input.set(String::new());` outside of the if statement so you dont have duplicates. Not blocking either

2023-02-20 19:31 UTC, dariusc93 commented on ui/src/components/friends/add.rs
> +                                    friend_input.set("".to_string());
```suggestion
                                    friend_input.set(String::new());
```

2023-02-20 19:31 UTC, dariusc93 commented on ui/src/components/friends/add.rs
> +                                    friend_input.set("".to_string());
```suggestion
                                    friend_input.set(String::new());
```

2023-02-20 19:31 UTC, dariusc93 commented on ui/src/components/friends/add.rs
> +                                    friend_input.set("".to_string());
```suggestion
                                    friend_input.set(String::new());
```

2023-02-20 19:31 UTC, dariusc93 commented on ui/src/components/friends/add.rs
> +                                    friend_input.set("".to_string());
```suggestion
                                    friend_input.set(String::new());
```

2023-02-20 19:31 UTC, dariusc93 commented on ui/src/components/friends/add.rs
> +                                    friend_input.set("".to_string());
What might be better would be to clear the input outside of the if statement. Would reduce duplicated code

2023-02-20 19:31 UTC, dariusc93 commented on ui/src/components/friends/add.rs
> +                                    friend_input.set("".to_string());
ditto

2023-02-20 19:55 UTC, dariusc93 submitted a review, later dismissed

2023-02-20 19:56 UTC, Jekrimo commented
> LGTM. Left a suggestion (though non-blocking) but something i think might be preferable to do would be to use `friend_input.set(String::new());` outside of the if statement so you dont have duplicates. Not blocking either

Thank you Darius! Got all those fixes in. I knew there had to be a better way!

2023-02-21 15:22 UTC, lgmarchi requested changes
I don't know if it is intended, but when I copy own DID and paste, it just clear with return, but it does not clear clicking in the button. 


https://user-images.githubusercontent.com/63157656/220385832-e68dbde2-edc9-4be5-b012-3f107e01fa7f.mov

2023-02-21 15:42 UTC, phillsatellite commented
> I don't know if it is intended, but when I copy own DID and paste, it just clear with return, but it does not clear clicking in the button.

Good find @lgmarchi Thanks for testing! 🥲

2023-02-21 15:49 UTC, Jekrimo commented
> 

I feel like this is a separate bug for it's own ticket? Or did it function before with an error and such?

2023-02-21 15:50 UTC, Jekrimo commented
> I feel like this is a separate bug for it's own ticket? Or did it function before with an error and such? & @lgmarchi

2023-02-21 17:59 UTC, lgmarchi commented
> I feel like this is a separate bug for it's own ticket? Or did it function before with an error and such?

I let it more as your decision my friend! If you prefer to solve it, in separated ticket, no problem for me. Just create other ticket for it and comment it if you want and I approve your PR. 

By the way, nice PR man!

2023-02-21 18:08 UTC, phillsatellite commented
Seems we might need a ticket for using Enter/Return to send a request which I can write up! On Dev the behavior is 

1. User hits enter/return key nothing happens/no error in console (Same for adding a friend)
2. User clicks "+Add" error will appear in console that says you cannot add yourself.

2023-02-21 18:11 UTC, dariusc93 commented
> Seems we might need a ticket for using Enter/Return to send a request which I can write up! On Dev the behavior is
> 
>     1. User hits enter/return key nothing happens/no error in console (Same for adding a friend)
> 
>     2. User clicks "+Add" error will appear in console that says you cannot add yourself.
> 
> 
> <img alt="Screenshot 2023-02-21 at 1 04 47 PM" width="576" src="https://user-images.githubusercontent.com/93608357/220425141-6b42bf7d-8571-4c52-83ac-143239d5bc73.png">

Odd. Does that happen when using a different DID?

2023-02-21 18:14 UTC, lgmarchi commented
> > Seems we might need a ticket for using Enter/Return to send a request which I can write up! On Dev the behavior is
> > ```
> > 1. User hits enter/return key nothing happens/no error in console (Same for adding a friend)
> > 
> > 2. User clicks "+Add" error will appear in console that says you cannot add yourself.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Screenshot 2023-02-21 at 1 04 47 PM" width="576" src="https://user-images.githubusercontent.com/93608357/220425141-6b42bf7d-8571-4c52-83ac-143239d5bc73.png">
> 
> Odd. Does that happen when using a different DID?

No Darius, this problem just happen with own DID, but not happens with own DID and when we press return on keyboard.

2023-02-21 21:38 UTC, phillsatellite commented
Hey dude! So with the last commits, it did fix the enter key after pasting did issue Lucas found but I did try the same flow but with clicking +Add instead of hitting the enter/return key and the did key persist after clicking 

str 
Copy/paste your own DID
_Click_ +add button
DID key persist 

https://user-images.githubusercontent.com/93608357/220464407-8280182e-d3eb-4916-881c-eca5b67cd539.mov

2023-02-22 00:10 UTC, Jekrimo commented
> Hey dude! So with the last commits, it did fix the enter key after pasting did issue Lucas found but I did try the same flow but with clicking +Add instead of hitting the enter/return key and the did key persist after clicking
> 
> str Copy/paste your own DID _Click_ +add button DID key persist

ok awesome, perfect! Back to not being able to add yourself, perfecto

2023-02-22 01:59 UTC, dariusc93 submitted a review, later dismissed

2023-02-22 14:29 UTC, lgmarchi submitted a review, later dismissed

2023-02-22 15:22 UTC, phillsatellite commented
I might have miscommunicated, when the user copies they're own DID and they _Click_ the "+Add" button the did will persist. After clicking "+add" the did should clear from the input box. Sorry if I confused things at all 

https://user-images.githubusercontent.com/93608357/220668069-4565d769-9da2-4666-85d1-2486bce914ae.mov

2023-02-22 21:05 UTC, phillsatellite approved these changes

2023-02-22 21:11 UTC, phillsatellite commented
Perfect on my side 🌟

2023-02-22 22:43 UTC, tooshel approved these changes

2023-02-23 03:53 UTC, dariusc93 approved these changes

2023-02-23 03:54 UTC, merged