Add chat soft return (for #308)
Satellite-im/Uplink pull request #336
Opened 2023-02-23 19:33 UTC by Flemmli97

### What this PR does 📖

- While holding shift and pressing enter adds a new line instead of sending the message
- Also fixes chat message not able to show new lines

### Which issue(s) this PR fixes 🔨

- Resolve #308

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-02-23 22:13 UTC, phillsatellite commented
Found a few things when testing but super neat so far! 🎉 

1. If you send a message with multiple lines, the size of the textbox will persist after sending message 

2. After you leave chat page and come back soft return seems to stop working 

https://user-images.githubusercontent.com/93608357/221042492-480cd5ee-15cb-4ed1-baf3-2afc064df068.mov

2023-02-26 03:18 UTC, dariusc93 approved these changes, later dismissed
Looks good to me from a glance over. I did leave a small suggestion but not non-breaking to the PR

2023-02-26 03:18 UTC, dariusc93 commented on kit/src/elements/input/mod.rs
> +        cx.props.allow_line_breaks.unwrap_or(false) && !cx.props.is_password.unwrap_or(false);
A bool, by default, would be `false` so unless those would be `true` by default (thus requiring an `unwrap_or` or similar to be set to `true` if those fields are `None`), its best to use `unwrap_or_default`

```suggestion
        cx.props.allow_line_breaks.unwrap_or_default() && !cx.props.is_password.unwrap_or_default();
```

2023-02-27 16:51 UTC, phillsatellite commented
Not sure if anyone else is able to replicate or not but I got 2 small errors when trying to pull the latest changes, tried clearing cache and rebuilding in case that might have been the problem but still no luck :( 

<img width="1353" alt="Screenshot 2023-02-27 at 11 49 05 AM" src="https://user-images.githubusercontent.com/93608357/221627396-689e6604-5320-45c3-9209-c8bb562b75e5.png">

2023-02-27 18:06 UTC, lgmarchi commented
> Not sure if anyone else is able to replicate or not but I got 2 small errors when trying to pull the latest changes, tried clearing cache and rebuilding in case that might have been the problem but still no luck 😕
> 
> <img alt="Screenshot 2023-02-27 at 11 49 05 AM" width="1353" src="https://user-images.githubusercontent.com/93608357/221627396-689e6604-5320-45c3-9209-c8bb562b75e5.png">

I am having same problem as you @phillsatellite

2023-02-27 18:10 UTC, lgmarchi requested changes
@Flemmli97 Merge last dev into your branch, so it can fix compile problem libp2p update and allow to test your changes. 

Dev was merged

2023-02-27 18:21 UTC, lgmarchi reviewed
Branch dev was merged and fixed libp2p problem when compile

2023-02-27 18:34 UTC, phillsatellite commented
Thanks for merging dev @lgmarchi! We actually tested together and found a few issues, we couldnt get soft return to work at all in chat, and when we paste DID on Friends page or we rename a file on Files page there will be a horizontal scrollbar that appears 

![image](https://user-images.githubusercontent.com/93608357/221652593-148138bb-f103-4f31-93ad-53a577078434.png)

https://user-images.githubusercontent.com/93608357/221652642-786df649-41db-4fca-a337-db3a0216d751.mov

2023-02-27 22:30 UTC, Flemmli97 commented
> 1. If you send a message with multiple lines, the size of the textbox will persist after sending message
> 2. After you leave chat page and come back soft return seems to stop working

should be fixed now

2023-02-28 00:41 UTC, Flemmli97 commented
one more thing: you cant horizontal drag the text if the text is too long.

i tried in a clean dioxus project using a textarea and by default you are unable to drag both vertically and horizontally which differs from what we have (vertical dragging works). idk whats different that allows it

https://user-images.githubusercontent.com/34157027/221722093-023e6c0a-bf36-4e8e-a6dc-1054d5c49f68.mp4

2023-02-28 15:59 UTC, phillsatellite approved these changes, later dismissed

2023-02-28 20:05 UTC, lgmarchi submitted a review, later dismissed

2023-03-01 02:10 UTC, dariusc93 approved these changes

2023-03-01 02:11 UTC, dariusc93 commented
Merging since it was previously approved with the only change was merging in dev (and resolving conflicts related to the imports)

2023-03-01 02:12 UTC, merged