feat(DragDrop): Drag drop upload files
Satellite-im/Uplink pull request #379
Opened 2023-03-03 18:53 UTC by lgmarchi

### What this PR does 📖
### 1. Upload files using drag and drop 

https://user-images.githubusercontent.com/63157656/222801679-cb3eb664-2216-43dc-a766-4f9dc65aa3b1.mov

### 2. Upload feedback works with file explorer as well 

https://user-images.githubusercontent.com/63157656/222801945-b5b9f329-d57a-48f1-b7ce-09ed2807fc07.mov

### 3. Fix small bug if folder name is very big
![image](https://user-images.githubusercontent.com/63157656/222802025-8b6689a2-fd3a-430e-b1e8-47dc5a0d9252.png)

- 

### Which issue(s) this PR fixes 🔨

- Resolve #346 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-03-03 21:45 UTC, phillsatellite commented
Hey Lucas! Worked perfect on MacOS! On Windows I had an issue 

When I drag and drop files in, you can see in the log that its registering me hovering/dropping the files but they will never actually appear in my uploaded files. Manually uploading still works fine though. I did try waiting a while for it to possibly update, closed and re opened the app and still nothing 

https://user-images.githubusercontent.com/93608357/222834483-cc066845-1161-4c1c-83d8-06b6b93ea2c2.mp4

2023-03-06 14:29 UTC, sdwoodbury commented
review in progress

2023-03-06 15:28 UTC, sdwoodbury requested changes
Nice work. I left some non-blocking suggestions. I know this isn't your fault but there's a ton of clippy warnings, all but one of which can be fixed automatically. I'll send over a patch. 

2 more non-blocking suggestions which might be better off in their own PRs
- the progress box might be more visually pleasing if in the center of the screen rather than the bottom left corner. 
- the file names on the storage page are hard to see because the font is so thin and so dark. a brighter and perhaps thicker font would help with this.

2023-03-06 15:28 UTC, sdwoodbury commented on common/src/warp_runner/manager/commands/constellation_commands.rs
> +                let image_thumb_uploaded =
when I upload something that isn't a picture or video, Uplink gives warning messages. This isn't a blocker but one alternative is to check the extension type before calling `set_thumbnail_if_file_is_image` or  `set_thumbnail_if_file_is_video`. This way, if those functions return an error, we then know that we should pay attention to it.  

I notice that the image extensions can be checked via  `ImageFormat::from_extension()` and video extensions can be compared to `VIDEO_FILE_EXTENSIONS`.

again, not a blocker. I'm fine if this isn't done at all or is done in another PR. 

![image](https://user-images.githubusercontent.com/8636602/223136236-b0fc609a-c88d-46e3-b01d-e4212c18b82b.png)

2023-03-06 15:28 UTC, sdwoodbury commented on common/src/warp_runner/manager/commands/constellation_commands.rs
> +                    match set_thumbnail_if_file_is_video(warp_storage, filename.clone(), file_path)
I tested the thumbnail functionality on Linux with an image and video. When I uploaded a `.mkv`, the thumbnail wasn't displayed. 

![image](https://user-images.githubusercontent.com/8636602/223137989-b6bfdd78-6716-4e76-af4c-3b995e117832.png)

![image](https://user-images.githubusercontent.com/8636602/223138239-1d5e80d8-dc71-4438-aa1c-634d89b05ca1.png)

2023-03-06 15:28 UTC, sdwoodbury commented on common/src/warp_runner/manager/commands/constellation_commands.rs
> +                    match set_thumbnail_if_file_is_video(warp_storage, filename.clone(), file_path)
ah, because I don't have ffmpeg

![image](https://user-images.githubusercontent.com/8636602/223144000-bfd6ab88-278c-465c-8990-04a7b6d55a99.png)

Maybe this isn't a problem. But we should make note of having ffmpeg as a dependency for later. We may need that information when creating an installer for Uplink.

2023-03-06 15:28 UTC, sdwoodbury commented on ui/src/layouts/storage.rs
> +}
not a blocker, but the built in functions for `Option`  could simplify the calculation of `file_name_formatted`  - mainly `unwrap_or_else`. 

```
fn format_item_name(file_name: String) -> String {
    let item = PathBuf::from(&file_name);

    let file_stem = item
        .file_stem()
        .and_then(OsStr::to_str)
        .map(str::to_string)
        .unwrap_or_default();

    file_name
        .get(0..15)
        .map(|x| x.to_string())
        .map(|x| {
            if file_stem.len() > MAX_LEN_TO_FORMAT_NAME {
                format!("{x}...")
            } else {
                x
            }
        })
        .unwrap_or_else(|| file_name.clone())
}
```

2023-03-06 15:28 UTC, sdwoodbury commented on ui/src/layouts/storage.rs
> +    let window = use_window(cx);
this is redundant. the same `window` was define on line 113.

2023-03-06 18:13 UTC, lgmarchi commented on common/src/warp_runner/manager/commands/constellation_commands.rs
> +                    match set_thumbnail_if_file_is_video(warp_storage, filename.clone(), file_path)
Opened a PR with instructions on readme!

https://github.com/Satellite-im/Uplink/pull/390

2023-03-06 18:50 UTC, sdwoodbury approved these changes

2023-03-06 19:27 UTC, phillsatellite approved these changes

2023-03-06 20:19 UTC, merged