feat(FilePreview): Possible to see a preview of Image, Video and PDF Files
Satellite-im/Uplink pull request #429
Opened 2023-03-10 02:42 UTC by lgmarchi

### What this PR does 📖

### 0. To get thumbnail from PDF files: 
It is necessary to install `pdftoppm` lib in our machines, but I am working on PDF and Video thumbnails to not need commands any more

To install this lib, command on macOS is: 

`brew install poppler`

### 1. Now is possible to see thumbnail in large sizes of video, image and pdf files 

https://user-images.githubusercontent.com/63157656/224209095-77b5fd9f-6671-4dcc-834e-a06964c2dd65.mov

### 2. Possible to change theme in main app, and file preview will change theme as well 

https://user-images.githubusercontent.com/63157656/224208929-c115b982-3657-4a64-bde5-aa30497f900a.mov

### 3. Independent of how many windows we have opened, when we close main app now, other windows will close too

https://user-images.githubusercontent.com/63157656/224208884-24abb9be-53ec-443e-af26-3e15c074006f.mov

- 

### Which issue(s) this PR fixes 🔨

- Resolve #255 

### Special notes for reviewers 🗒️

### Additional comments 🎤

## Video and PDF files are using command, in next PR, I will work to find a solution to be possible just use crate and do not need to use commands for them

2023-03-10 20:47 UTC, phillsatellite commented
Hey Lucas! Just a quick question, for the Video files when we preview I noticed it the video but never actually plays 

https://user-images.githubusercontent.com/93608357/224424603-279766a3-ac42-49ba-a7a8-002bb36646e4.mov

2023-03-10 21:08 UTC, sdwoodbury commented
> Hey Lucas! Just a quick question, for the Video files when we preview I noticed it the video but never actually plays

It seems like for a preview, not playing the video would be OK. This code is displaying a thumbnail image in a new window, but it hasn't downloaded the file. Without doing that, playing a video is not possible. 

If we want to play the video, it should be possible. We'd just have to fetch the file from IPFS. The CID is included in the `File` struct.

2023-03-10 21:24 UTC, sdwoodbury requested changes
I like the feature. I think the window management needs some changes. 
- If I close the main window, the child window doesn't automatically close. 
- State only tracks one window ID for file previews, but I can open multiple file previews. If I close the main window, Uplink won't know the window IDs of all the windows it needs to close.

2023-03-14 13:52 UTC, lgmarchi commented
> > Hey Lucas! Just a quick question, for the Video files when we preview I noticed it the video but never actually plays
> 
> It seems like for a preview, not playing the video would be OK. This code is displaying a thumbnail image in a new window, but it hasn't downloaded the file. Without doing that, playing a video is not possible.
> 
> If we want to play the video, it should be possible. We'd just have to fetch the file from IPFS. The CID is included in the `File` struct.

It could be done in a next PR.

2023-03-14 15:19 UTC, sdwoodbury commented
review in progress

2023-03-14 18:21 UTC, sdwoodbury approved these changes

2023-03-14 18:21 UTC, sdwoodbury commented on common/src/state/ui.rs
> +
I forgot to remove this in the PR. It's dead code at this point.

2023-03-14 20:24 UTC, phillsatellite commented
@lgmarchi Hey my friend, so when re-tested I found some things. I think most can probably be fixed in a future PR but the one I was concerned about is the Windows issue

MacOS will close all the previews when I close the app but there will be an error in console (this seems to be different than the error we talked about in chat)

<img width="574" alt="Screenshot 2023-03-14 at 4 05 43 PM" src="https://user-images.githubusercontent.com/93608357/225127555-7112184e-cb5f-4b17-bde7-e233894a090d.png">

On **Linux** when I closed the app the previews remained open and I had to close them manually 

https://user-images.githubusercontent.com/93608357/225126709-89f3c619-641a-4109-8f6f-2cb693ae02c6.mov


On **Windows** the file preview seemed to have broke all together

https://user-images.githubusercontent.com/93608357/225126569-6aee8cb8-1d51-462c-ad5c-4c59ceae5973.mov

2023-03-15 18:50 UTC, dariusc93 commented
> MacOS will close all the previews when I close the app but there will be an error in console (this seems to be different than the error we talked about in chat)
> 
> <img alt="Screenshot 2023-03-14 at 4 05 43 PM" width="574" src="https://user-images.githubusercontent.com/93608357/225127555-7112184e-cb5f-4b17-bde7-e233894a090d.png">
> 
The error seems related to #441 , which may not be related to this PR but something separately

2023-03-15 19:06 UTC, phillsatellite commented
Currently reviewing again, right now on Windows the file preview seems to work again. Going to investigate a little more on  Windows and other OS's

2023-03-15 19:31 UTC, phillsatellite approved these changes

2023-03-15 19:33 UTC, phillsatellite commented
Approved on my side the preview worked on all the OS's / VM's I could still replicate the previews persisting after closing the app on Linux and Windows I can create a ticket for that 👍

2023-03-15 20:39 UTC, lgmarchi commented
> @lgmarchi Hey my friend, so when re-tested I found some things. I think most can probably be fixed in a future PR but the one I was concerned about is the Windows issue
> 
> MacOS will close all the previews when I close the app but there will be an error in console (this seems to be different than the error we talked about in chat)
> 
> <img alt="Screenshot 2023-03-14 at 4 05 43 PM" width="574" src="https://user-images.githubusercontent.com/93608357/225127555-7112184e-cb5f-4b17-bde7-e233894a090d.png">
> 
> On **Linux** when I closed the app the previews remained open and I had to close them manually
> 
> On **Windows** the file preview seemed to have broke all together. I tested this on a Windows VM and actual Windows both Windows 11 tested with old and new accounts.

It will be better to treat those problems in other PR, specific for each platform, thanks for all tests my friend!

2023-03-16 17:35 UTC, merged