fix(input): add num pad enter to keyup
Satellite-im/Uplink pull request #463
Opened 2023-03-15 21:18 UTC by Jekrimo

### What this PR does 📖

- 

### Which issue(s) this PR fixes 🔨

- Resolve #453 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-03-16 13:45 UTC, phillsatellite approved these changes, later dismissed

2023-03-16 13:45 UTC, phillsatellite commented
Good across all OS's 💯

2023-03-16 17:47 UTC, sdwoodbury requested changes
we should do this for `textarea::Input` also

2023-03-18 15:19 UTC, Jekrimo commented
> we should do this for `textarea::Input` also

good looking out, totally forgot about the textarea! updated

2023-03-20 14:52 UTC, sdwoodbury approved these changes

2023-03-20 14:58 UTC, merged