fix(chat): Save the last active chat when switching tabs
Satellite-im/Uplink pull request #472
Opened 2023-03-17 17:03 UTC by Flemmli97

### What this PR does 📖

- Saves the uuid of the active chat when one switches to another tabs so when it switches back it still shows the chat
- The uuid is saved in the chats struct of `chats.rs` as `last_active` so it also persists over saves

### Which issue(s) this PR fixes 🔨

- Resolve #459

2023-03-17 19:59 UTC, phillsatellite approved these changes

2023-03-20 14:37 UTC, sdwoodbury requested changes
Adding an extra variable to state is unnecessary. The problem is here
![image](https://user-images.githubusercontent.com/8636602/226372169-e42142be-dae1-408e-a87e-3a2206f81aa3.png)

This was introduced by commit `0cc5161402543020d4d6833d5fbb1790fec66767`. All we have to do is revert that change. `Action::ClearChat` shouldn't be called when one leaves the Chats view.

2023-03-20 18:31 UTC, Flemmli97 commented
> Adding an extra variable to state is unnecessary. The problem is here ![image](https://user-images.githubusercontent.com/8636602/226372169-e42142be-dae1-408e-a87e-3a2206f81aa3.png)
> 
> This was introduced by commit `0cc5161402543020d4d6833d5fbb1790fec66767`. All we have to do is revert that change. `Action::ClearChat` shouldn't be called when one leaves the Chats view.

i added an extra state since i wasnt sure if removing that line causes other issues as then the active chat will be always present. even if e.g. you are in another tab

2023-03-20 20:04 UTC, sdwoodbury commented
> > Adding an extra variable to state is unnecessary. The problem is here ![image](https://user-images.githubusercontent.com/8636602/226372169-e42142be-dae1-408e-a87e-3a2206f81aa3.png)
> > This was introduced by commit `0cc5161402543020d4d6833d5fbb1790fec66767`. All we have to do is revert that change. `Action::ClearChat` shouldn't be called when one leaves the Chats view.
> 
> i added an extra state since i wasnt sure if removing that line causes other issues as then the active chat will be always present. even if e.g. you are in another tab
> 
> edit: the linked commit does indeed depend on it.

[This](https://github.com/Satellite-im/Uplink/blob/dev/common/src/state/ui.rs#L58) can probably be used instead. If the current layout isn't `Compose` then a notification should be played.

2023-03-21 11:05 UTC, Flemmli97 commented
> > > Adding an extra variable to state is unnecessary. The problem is here ![image](https://user-images.githubusercontent.com/8636602/226372169-e42142be-dae1-408e-a87e-3a2206f81aa3.png)
> > > This was introduced by commit `0cc5161402543020d4d6833d5fbb1790fec66767`. All we have to do is revert that change. `Action::ClearChat` shouldn't be called when one leaves the Chats view.
> > 
> > 
> > i added an extra state since i wasnt sure if removing that line causes other issues as then the active chat will be always present. even if e.g. you are in another tab
> > edit: the linked commit does indeed depend on it.
> 
> [This](https://github.com/Satellite-im/Uplink/blob/dev/common/src/state/ui.rs#L58) can probably be used instead. If the current layout isn't `Compose` then a notification should be played.

A lot of places seem to assume active chat = chat that is currently open. Some examples are e.g. 
in `common::src::state::chats.rs#active_chat_has_unreads` or `#get_replying_to` etc. The comment for the field itself says this too. So changing this implication seems to break quite a bit of stuff.

2023-03-21 14:00 UTC, sdwoodbury commented
I maintain that `State` doesn't need any new variables. I believe that fixing notifications could have been a 1 line change (before the bug was introduced). I submitted an alternative PR here: https://github.com/Satellite-im/Uplink/pull/481.

2023-03-21 15:40 UTC, sdwoodbury commented
closed in favor of #481

2023-03-21 15:40 UTC, closed without merging