feat(chat): Attachment visualizer
Satellite-im/Uplink pull request #728
Opened 2023-04-26 11:50 UTC by Flemmli97

### What this PR does 📖

- This is the draft for having attachment embeds in chat. Will show a preview of the attachment of messages
- Currently due to warp not providing any thumbnail/picture for files it wont do anything
- Current status of the PR includes the ui part such that if warp does provide the missing things it should work out of the box. It uses `warp::constellation::file::File#thumbnail` which is currently never set by warp to obtain a path to the file thumbnail.
- To test the current impl one can replace the thumbnail value in `kit::components::file_embed::mod.rs#68` with the following to use the current profile pic:
```rust
    let state = use_shared_state::<State>(cx)?;
    let thumbnail = state.read().get_own_identity().profile_picture();
```

### Which issue(s) this PR fixes 🔨

- Resolve #524

2023-05-16 20:56 UTC, stavares843 commented
**AI CODE REVIEW**

Feedback on code changes:

Patch 1/5:

The code changes in mod.rs file of the file_embed component and the associated style.scss files seem fine.
The changes include adding a new thumbnail prop to the Props struct, handling the thumbnail prop in the component rendering logic, and updating the associated styles.
The code appears to do what it says in the commit message, which is adding attachment rendering functionality.
Patch 2/5:

The code changes in mod.rs and style.scss files of the file_embed component and mod.rs and style.scss files of the message and message_reply components seem reasonable.
The changes include adding a new big prop to the Props struct of the file_embed component, updating the rendering logic to handle the big prop, and adjusting styles accordingly.
The code appears to make the attachment embed look nicer by providing an option to display a larger image if the big prop is set to true.
Patch 3/5:

The code change in mod.rs file of the file_embed component looks fine.
The change removes an unused import, which is a good cleanup.
The code appears to address a Clippy warning or unused code.
Patch 4/5:

The code changes in mod.rs files of the message, message_reply, and chatbar components seem fine.
The changes include adding the thumbnail prop to the Props struct of the message component and handling it in the component's rendering logic.
The code appears to introduce the use of the thumbnail for files in messages.
Overall, the code changes in the patches seem reasonable and align with their respective commit messages. No bugs or major issues are found.

2023-05-19 20:43 UTC, dariusc93 commented on kit/src/components/file_embed/mod.rs
> +    big: Option<bool>,
Would this be better to just be a boolean instead?

2023-05-20 00:14 UTC, dariusc93 approved these changes

2023-05-20 15:30 UTC, stavares843 commented
**AI CODE REVIEW**

Feedback on the code changes:

Overall, the code changes look good and seem to align with the commit messages.
In the FileEmbed component in mod.rs, the changes introduce a new thumbnail property, which is optional. The code handles the presence of a thumbnail and renders it accordingly.
There are some style changes in the SCSS files, primarily related to the file_embed and message components.
In file_embed/style.scss, there is a new .image-container class introduced, which positions the image and download button correctly.
In file_embed/mod.rs, the big property is added to the Props struct and used to determine if the file embed should be rendered with a larger size. It is passed down to the FileEmbed component and used to conditionally apply the big class in the rendered HTML.
In message/mod.rs, the thumbnail property is passed down to the FileEmbed component, allowing it to display the thumbnail of the file.
In message_reply/style.scss, there are some minor style changes related to alignment.
In file_embed/mod.rs, the import of common::state::State is no longer needed and can be removed.

2023-05-20 15:31 UTC, stavares843 commented
In file_embed/mod.rs, the import of common::state::State is no longer needed and can be removed.

is that accurate?

2023-05-20 15:35 UTC, stavares843 reviewed
https://github.com/Satellite-im/Uplink/assets/29093946/aa2147d0-7647-435e-984c-98e5f2856689

is it possible to improve the size of the preview? atm is somewhat big, even when sending very small files like favicons always display the same size

macOS, m1

2023-05-20 15:41 UTC, stavares843 requested changes
sending specific images crash's


crash log
https://gist.github.com/stavares843/35e8cf30f331acba46ae6c6c9669bb83

macOS, m1

image (zipped)

[2B986EBC-A8C4-4C68-BF5D-0F5CBFB1ACB1.png.zip](https://github.com/Satellite-im/Uplink/files/11522667/2B986EBC-A8C4-4C68-BF5D-0F5CBFB1ACB1.png.zip)

flow
- unzip
- drag to chat
- send

the crash happens after sending, display the loading and then before displaying the image crash's

doesn't crash on dev because theres no image preview in chat in dev

2023-05-20 16:19 UTC, dariusc93 commented
> Gravacao.do.ecra.2023-05-20.as.16.34.29.mov
> 
> is it possible to improve the size of the preview? atm is somewhat big, even when sending very small files like favicons always display the same size
> 
> macOS, m1

That will be something ill handle on my end in a different update on warp (notice this while testing this branch).

2023-05-21 04:09 UTC, dariusc93 commented
> sending specific images crash's
> 
> crash log https://gist.github.com/stavares843/35e8cf30f331acba46ae6c6c9669bb83
> 
> macOS, m1
> 
> image (zipped)
> 
> [2B986EBC-A8C4-4C68-BF5D-0F5CBFB1ACB1.png.zip](https://github.com/Satellite-im/Uplink/files/11522667/2B986EBC-A8C4-4C68-BF5D-0F5CBFB1ACB1.png.zip)
> 
> flow
> 
>     * unzip
> 
>     * drag to chat
> 
>     * send
> 
> 
> the crash happens after sending, display the loading and then before displaying the image crash's
> 
> doesn't crash on dev because theres no image preview in chat in dev

I havent been able to reproduce this on my mac

2023-05-22 16:52 UTC, phillsatellite commented
> > sending specific images crash's
> > crash log https://gist.github.com/stavares843/35e8cf30f331acba46ae6c6c9669bb83
> > macOS, m1
> > image (zipped)
> > [2B986EBC-A8C4-4C68-BF5D-0F5CBFB1ACB1.png.zip](https://github.com/Satellite-im/Uplink/files/11522667/2B986EBC-A8C4-4C68-BF5D-0F5CBFB1ACB1.png.zip)
> > flow
> > ```
> > * unzip
> > 
> > * drag to chat
> > 
> > * send
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the crash happens after sending, display the loading and then before displaying the image crash's
> > doesn't crash on dev because theres no image preview in chat in dev
> 
> I havent been able to reproduce this on my mac

I could not get it to crash but I could not get attachment to appear when sent 

Mac m2 
OS 13.3.1 

![2B986EBC-A8C4-4C68-BF5D-0F5CBFB1ACB1](https://github.com/Satellite-im/Uplink/assets/93608357/a1cf8905-6ba6-49cd-81ad-52830520adbb)

2023-05-22 17:30 UTC, Flemmli97 commented
tested on linux. works for both attachments send and received

2023-05-24 16:07 UTC, Flemmli97 commented
tested on mac. same behaviour as phill. no thumbnail. the thumbnail field for files is empty.

2023-05-24 16:08 UTC, Flemmli97 commented
also regarding image size: images get clamped to a max of 700x700 px. smaller images will render smaller. currently it seems all thumbnail images from warp are 500x500

2023-05-24 16:38 UTC, dariusc93 commented
![image](https://github.com/Satellite-im/Uplink/assets/3918024/5d7b3f05-2391-4c59-9818-209e17ff8962)

It appears fine for me, but i do know some images had issues being encoded, which would lead to some not showing up. May be more of issue with the library being used and would require additional work for those set of images, which can come a bit later. 

As for the dimensions, in warp its set for 128x128 for thumbnails, but i increased it to 500x500 in uplink. I did forget to add a check in for the dimensions before resizing so that will be added in a shortly.

2023-05-25 10:54 UTC, Flemmli97 commented
it was just a plain png i used.
on mac air. 12.6.4

2023-05-25 18:35 UTC, dariusc93 commented
> it was just a plain png i used. on mac air. 12.6.4

If it was similar to what @stavares843 was using, then i will probably also work in a workaround for that. I think its good to merge it in though and i can bring the changes over to correct a couple of things shortly.

2023-05-25 19:51 UTC, stavares843 commented
sounds good 🔨

2023-05-25 19:51 UTC, stavares843 commented
**AI CODE REVIEW**


Review of code changes:

Commit 1/5:

Adds a new prop thumbnail to the Props struct in file_embed/mod.rs.
Adds support for rendering a thumbnail image if it exists.
Changes the layout of the file embed based on the presence of a thumbnail.
Fixes an issue where the with_download_button prop was not being used correctly.
The code changes appear to align with the commit message.
Commit 2/5:

Makes improvements to the styling of the file embed component.
Adds support for a larger image display with the addition of the big prop.
Modifies the CSS rules for the image container and image elements.
Changes the maximum width and height of the image based on the big prop.
The code changes appear to align with the commit message.
Commit 3/5:

Removes an unused import statement in file_embed/mod.rs.
The code change appears to align with the commit message.
Commit 4/5:

Adds support for rendering the thumbnail of a file in the message component.
Modifies the Props struct in message/mod.rs to include the thumbnail prop.
Passes the thumbnail prop to the file embed component.
The code change appears to align with the commit message.
Overall, the code changes seem to implement the described features and improvements. No bugs or major issues are apparent.

2023-05-29 16:31 UTC, stavares843 commented
do we wanna address any other changes here?

2023-05-31 16:17 UTC, stavares843 commented
cc @Flemmli97 let us know if this is ready to do code review and testing

2023-05-31 16:37 UTC, Flemmli97 commented
> cc @Flemmli97 let us know if this is ready to do code review and testing

thought it was good to go according to darius

2023-05-31 16:39 UTC, stavares843 commented
awesome, thanks 🎉

2023-05-31 16:47 UTC, stavares843 approved these changes

2023-05-31 16:47 UTC, merged