update(ChatBar): Add message when user reach maximum of 1024 chars
Satellite-im/Uplink pull request #736
Opened 2023-04-27 12:20 UTC by lgmarchi

### What this PR does 📖
### 1. Add message when user reach maximum of 1024 chars

https://user-images.githubusercontent.com/63157656/234915855-2b7d4ac6-bdfb-486b-b63f-ba7f438ffa66.mov

- 

### Which issue(s) this PR fixes 🔨

- Resolve #591 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-04-27 16:06 UTC, stavares843 reviewed
seems we can still add 2 more chars when the error appears


https://user-images.githubusercontent.com/29093946/234921332-b6586433-aeba-424f-aadc-bc120fced61d.mp4



macOS

2023-04-27 18:30 UTC, lgmarchi commented
> seems we can still add 2 more chars when the error appears
> 
>  Screen.Recording.2023-04-27.at.5.05.54.PM.mp4 
> macOS

@stavares843 about this, I made purpose to allow until 1025 chars, because sometimes happen a bug and you can not type last char. 

For example if I let max as 1024, sometimes will stop on 1023 and will not show message to the user. 

I did this way, because I think it is better to has a feedback. What is your opinion?

2023-04-27 19:37 UTC, phillsatellite commented
Hey @lgmarchi just a small request from my side, after the User sends the message the error message will persist after message is sent. It will also persist when switching through chats 

https://user-images.githubusercontent.com/93608357/234972356-8a9710a5-9438-4cb1-a77c-cd243ae301aa.mov

2023-04-28 16:38 UTC, lgmarchi commented
> Hey @lgmarchi just a small request from my side, after the User sends the message the error message will persist after message is sent. It will also persist when switching through chats
> 
>  Screen.Recording.2023-04-27.at.3.23.05.PM.mov

Fixed man!

2023-05-01 15:59 UTC, phillsatellite approved these changes

2023-05-01 16:31 UTC, tooshel commented on ui/src/components/chat/compose/chatbar.rs
> +    if value_chatbar.len() >= 1024 && !error.0 {
Why don't we use that default prop above (which is in another file but still) so if we want to change it later we can change it in just one place?

2023-05-01 18:07 UTC, lgmarchi commented on ui/src/components/chat/compose/chatbar.rs
> +    if value_chatbar.len() >= 1024 && !error.0 {
This is a particular case for chatBar, it does not receive Validation, and error is just maximum chars to 1024. I didn't see needs to do it in other file and be reusable. 

And particular for chatbar, it is not using dioxus states inside, so avoided to use it as well.

2023-05-01 21:56 UTC, dariusc93 approved these changes

2023-05-02 13:50 UTC, sdwoodbury requested changes
i noticed that `error.1` isn't evaluated before displaying the error message. In other words, it looks like an error message for the wrong chat could be displayed.

2023-05-02 13:54 UTC, sdwoodbury approved these changes
looks like I was wrong about that bug, though I don't know why. I'll approve to unblock the PR but I still think that part could use improvement.

2023-05-02 14:21 UTC, merged