feat(chat): Expand group click area
Satellite-im/Uplink pull request #848
Opened 2023-05-30 12:52 UTC by Flemmli97

### What this PR does 📖

- Expands click area to show group list in a group chat to the whole top bar

### Which issue(s) this PR fixes 🔨

- Resolve #816

2023-05-30 14:13 UTC, phillsatellite commented
Just one minor suggestion from my end, in PR basically the entire top of chat is clickable to see the group list 

https://github.com/Satellite-im/Uplink/assets/93608357/0412fa87-d201-4d11-b43a-bfc99d285caf


maybe we only need this area clickable 
![image](https://github.com/Satellite-im/Uplink/assets/93608357/7b6c5aec-9fc0-4506-b763-684d8e125997)

2023-05-30 14:22 UTC, stavares843 commented
same 🔨

2023-05-30 14:58 UTC, Flemmli97 commented
i thought the goal of the issue was to make the whole thing clickable. as the current stand is just that area being clickable.

2023-05-30 14:59 UTC, stavares843 commented
i added the ticket, the goal isn't the whole area just the area as the one phil added a screenshot for

2023-05-30 18:06 UTC, Flemmli97 commented
hmm then im confused as what phill described is the way it currently works

this is on dev:


https://github.com/Satellite-im/Uplink/assets/34157027/84e09f7f-6543-49b7-98d6-72b65e3ad143

2023-05-31 11:03 UTC, stavares843 commented
if you notice in second 8 and 9 you clicked and group wasn't displayed 

thats what the ticket was meant to improve

2023-05-31 15:37 UTC, WanderingHogan requested changes, later dismissed
move onclick into child div

2023-05-31 15:37 UTC, WanderingHogan commented on kit/src/layout/topbar/mod.rs
> +            onclick: move |_| {
can you move this onclick into the div below that has the children class

2023-05-31 16:41 UTC, WanderingHogan commented
@Flemmli97 - @stavares843 and @tooshel are going to mess around with mac versions to see if this is an issue with updated macos 12 (the issue is only seen, as far as we can tell, in macos 12.0), and then they will decide what our targets are, and then if this is even an issue with those targets, either come back with more information, accept this fix, or close the ticket because it's no longer an issue

hopefully in the future with targets defined, we will know if issues are actually bugs on whatever targets they define so there is less ambiguity

2023-05-31 23:24 UTC, stavares843 commented
so after testing it wasn't a issue with 12, it also happens in the latest - 13.4

2023-05-31 23:25 UTC, stavares843 commented
retesting pr again with the latest code changes

2023-05-31 23:35 UTC, stavares843 approved these changes

2023-05-31 23:35 UTC, stavares843 commented
fixed 🎉

2023-05-31 23:35 UTC, phillsatellite approved these changes

2023-05-31 23:35 UTC, merged