Radio list
Satellite-im/Uplink pull request #955
Opened 2023-07-05 18:18 UTC by InfamousVague

### What this PR does 📖

Adds a radio list of options. This is intended to be a good starting point without the need for @sdwoodbury to fiddle with creating new designs or components. 
<img width="908" alt="image" src="https://github.com/Satellite-im/Uplink/assets/1770198/b7b2a9c5-db2d-4fa2-b063-a04c4629d6a7">

2023-07-05 19:39 UTC, dariusc93 requested changes
can you revert the `Cargo.lock` back to what is used on dev?

2023-07-05 19:39 UTC, dariusc93 commented on kit/src/elements/radio_list/mod.rs
> +    let internal_state = use_state(&cx, || cx.props.initial_value.clone());
Just so clippy dont complain

```suggestion
    let internal_state = use_state(cx, || cx.props.initial_value.clone());
```

2023-07-06 00:01 UTC, dariusc93 approved these changes

2023-07-06 16:18 UTC, phillsatellite approved these changes

2023-07-06 17:27 UTC, sdwoodbury approved these changes

2023-07-06 17:27 UTC, merged