update(Link): Get more information as possible from links
Satellite-im/Uplink pull request #985
Opened 2023-07-14 13:44 UTC by lgmarchi

### What this PR does 📖
### 1. Get more information as possible from links
- Try other ways to get link icon
- Try different ways to get link description 
- It doesn't show Icon, if icon does not exist 

![image](https://github.com/Satellite-im/Uplink/assets/63157656/c9c571cb-b30a-4985-94e2-2e2ba08abd30)
![image](https://github.com/Satellite-im/Uplink/assets/63157656/0030ee78-03ba-436b-bd05-e5a0b9ebee13)

### Which issue(s) this PR fixes 🔨

- Resolve #978 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2023-07-14 18:12 UTC, phillsatellite commented
Can approve once conflicts are gone 💥  Awesome feature bro @lgmarchi

2023-07-14 18:16 UTC, phillsatellite approved these changes

2023-07-14 19:53 UTC, stavares843 approved these changes

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/get_link_data.rs
> +                image = Some(content_attr.to_string());
If there are multiple fields with the attribute, are we looking to set the first attribute? If so, we could just return early here.

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/get_link_data.rs
> +pub async fn get_title_data(document: Html, meta_selector: Selector) -> String {
No need to be async if nothing is awaiting. 

```suggestion
pub fn get_title_data(document: Html, meta_selector: Selector) -> String {
```

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/mod.rs
> +    let title = get_title_data(document.clone(), meta_selector.clone()).await;
```suggestion
    let title = get_title_data(document.clone(), meta_selector.clone());
```

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/get_link_data.rs
> +pub async fn get_description_data(document: Html, meta_selector: Selector) -> String {
Ditto for not needing an async signature if nothing in the function is awaiting
```suggestion
pub fn get_description_data(document: Html, meta_selector: Selector) -> String {
```

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/mod.rs
> +    let description = get_description_data(document.clone(), meta_selector.clone()).await;
```suggestion
    let description = get_description_data(document.clone(), meta_selector.clone());
```

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/get_link_data.rs
> +pub async fn get_image_data(document: Html, meta_selector: Selector) -> Option<String> {
```suggestion
pub fn get_image_data(document: Html, meta_selector: Selector) -> Option<String> {
```

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/mod.rs
> +                    .await
```suggestion
```

2023-07-17 15:18 UTC, dariusc93 commented on kit/src/components/embeds/link_embed/mod.rs
> +            .await
```suggestion
```

2023-07-17 15:25 UTC, sdwoodbury requested changes

2023-07-17 15:25 UTC, sdwoodbury commented on kit/src/components/embeds/link_embed/get_link_data.rs
> +pub async fn get_image_data(document: Html, meta_selector: Selector) -> Option<String> {
might want to break out  of the loop when the first image is detected. otherwise the last image will be returned.

2023-07-17 15:25 UTC, sdwoodbury commented on kit/src/components/embeds/link_embed/get_link_data.rs
> +pub async fn get_title_data(document: Html, meta_selector: Selector) -> String {
might want to break out of the loop when the first title is detected

2023-07-17 15:25 UTC, sdwoodbury commented on kit/src/components/embeds/link_embed/get_link_data.rs
> +pub async fn get_description_data(document: Html, meta_selector: Selector) -> String {
same thing about breaking out of the loop

2023-07-17 15:25 UTC, sdwoodbury commented on kit/src/components/embeds/link_embed/mod.rs
> +    let icon = match fetch_icon(url, document.clone()).await {
this code is hard to follow. proposed change: 
```
let icon = if let Ok(Some(d)) = fetch_icon(url, document.clone()).await {
        d
    } else {
        get_image_data(document.clone(), meta_selector.clone())
            .await
            .unwrap_or_default()
    };
    ```

2023-07-17 17:12 UTC, sdwoodbury approved these changes

2023-07-17 19:49 UTC, dariusc93 approved these changes

2023-07-17 19:51 UTC, merged